const fs = require('fs');
const assert = require('assert');

const source = fs.readFileSync(__dirname + '/wood-kitchen-template.html', 'utf8');
const renameSource = fs.readFileSync(__dirname + '/wood-rename.html', 'utf8');

assert.match(renameSource, /sub2c:\s*'wood-kitchen-template\.html\?type=calendar&return=sub2c'/, '节日节气应进入专用页面');
assert.match(source, /calendar:\s*\{[\s\S]{0,500}categories:\s*\['十二节气', '重要节日', '纪念日', '生日', '特殊日记录'\]/, '节日节气应提供五个默认序列');
assert.match(source, /function renderCalendarStats/, '节日节气应使用专用统计方块渲染');
assert.match(source, /function sameMonthDay/, '纪念日、生日和特殊日应按月日匹配');
assert.match(source, /calendarCategoryRoles/, '序列名称修改后应保留稳定分类标识');
assert.match(source, /function renameCategory[\s\S]{0,360}calendarCategoryRoles/, '重命名序列时应同步更新稳定分类标识');
assert.match(source, /function calendarWeekdayText[\s\S]{0,180}星期/, '第一个方块应显示星期');
assert.match(source, /function calendarLunarDateText[\s\S]{0,260}u-ca-chinese/, '第一个方块应使用浏览器农历日期');
assert.match(source, /calendarStatData[\s\S]{0,1800}calendarRecords\(\['solar'\][\s\S]{0,300}calendarRecords\(\['holiday'\][\s\S]{0,500}calendarRecords\(\['memorial'\][\s\S]{0,300}calendarRecords\(\['birthday'\][\s\S]{0,500}calendarRecords\(\['special'\]/, '四个方块应分别匹配节气、节日、纪念日、生日和特殊日');
assert.match(source, /\.calendar-stat\s*\{[^}]*height:\s*69px/, '四个日历方块应使用统一高度');
assert.match(source, /\.calendar-stat \.stat-count\s*\{[^}]*font-size:\s*12px/, '日历方块文字过长时应缩小字号');
assert.match(source, /\.calendar-stat \.stat-count\s*\{[^}]*overflow:\s*hidden/, '日历方块文字过长时应限制溢出');
assert.match(source, /class="calendar-date"/, '节日节气标题右侧应显示实时日期');
assert.match(source, /function calendarHeaderDateText[\s\S]{0,260}年[\s\S]{0,120}月[\s\S]{0,120}日/, '标题日期应使用年月日格式');
assert.match(source, /title:\s*calendarWeekdayText\(now\),\s*note:\s*calendarLunarDateText\(now\)/, '第一个方块应显示星期并在底部显示农历');
assert.match(source, /\.calendar-date\s*\{[^}]*color:\s*#5a4632[^}]*font-size:\s*14px[^}]*font-weight:\s*800[^}]*letter-spacing:\s*0\.01em/, '标题日期应与标题同色同字重并缩小字间距');
assert.match(source, /\.calendar-date\s*\{[^}]*margin-left:\s*6px[^}]*;/, '标题与日期之间应保留小间距');
assert.match(source, /return date\.getFullYear\(\) \+ '年' \+ \(date\.getMonth\(\) \+ 1\) \+ '月' \+ date\.getDate\(\) \+ '日'/, '日期内部不应包含多余空格');
assert.match(source, /var calendarSolarTerms\s*=\s*\[[\s\S]{0,2400}立春[\s\S]{0,2400}冬至/, '十二节气序列应内置完整二十四节气数据');
assert.match(source, /calendar:\s*\{[\s\S]{0,180}records:\s*calendarSolarTerms\.concat\(calendarHolidays\)/, '节日数据应导入节日节气页面');
assert.match(source, /\.calendar-solar-items\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)/, '二十四节气项目应两列显示');
assert.strictEqual((source.match(/id:\s*5\d{3},\s*category:\s*'十二节气'/g) || []).length, 24, '二十四节气数据应保持二十四条');
assert.match(source, /\.calendar-solar-items\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)/, '二十四节气项目应两列显示');
assert.match(source, /name:\s*'1月5日 小寒'/, '节气日期应使用月日格式');
assert.doesNotMatch(source, /name:\s*'1\.5 小寒'/, '节气名称不应继续使用点号日期格式');
assert.match(source, /var calendarHolidays\s*=\s*\[[\s\S]{0,2600}国庆节[\s\S]{0,2600}圣诞节/, '重要节日序列应包含国内和国际常见节日');
assert.match(source, /records:\s*calendarSolarTerms\.concat\(calendarHolidays\)/, '节日数据应导入重要节日序列');
assert.match(source, /\.calendar-holiday-items\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)/, '重要节日项目应两列显示');
assert.match(source, /\.calendar-date-items\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)/, '纪念日、生日和特殊日项目应两列显示');
assert.match(source, /\.calendar-date-items \.item\s*\{[^}]*min-height:\s*38px/, '纪念日、生日和特殊日方块应与前两个序列统一高度');
assert.match(source, /currentCalendarRole === 'solar' \|\| currentCalendarRole === 'holiday' \|\| currentCalendarRole === 'memorial' \|\| currentCalendarRole === 'birthday' \|\| currentCalendarRole === 'special'/, '五个日历序列都应按月份排序');
assert.match(source, /name:\s*'2\.14 情人节'/, '重要节日应包含情人节并使用点号日期');
assert.doesNotMatch(source, /name:\s*'2月14日 情人节'/, '重要节日名称不应使用月日文字格式');
assert.match(source, /function normalizeCalendarHolidayName[\s\S]{0,260}match\(/, '已有节日记录应自动迁移为点号日期格式');
assert.match(source, /var calendarHolidayAnnualDates\s*=\s*\{[\s\S]{0,1200}2026[\s\S]{0,800}5120:\s*'2026-09-25'/, '农历节日应维护年度日期表');
assert.match(source, /function calendarDateValue[\s\S]{0,260}annualDates/, '节日日期匹配应优先读取当前年份日期');
assert.match(source, /matcher\(calendarDateValue\(record, now\.getFullYear\(\)\), now\)/, '节日匹配应使用当前年份');
assert.match(source, /function calendarMonthDayKey[\s\S]{0,220}match\[1\][\s\S]{0,80}match\[2\]/, '节日排序应只比较月份和日期');
assert.match(source, /sort\(function\(left, right\)\s*\{\s*return calendarMonthDayKey\(left\)/, '节日列表应按月日排序');
assert.match(source, /function calendarStatData[\s\S]{0,2200}calendarLunarDateText\(now\)[\s\S]{0,700}纪念日 生日[\s\S]{0,500}特殊日/, '四个统计方块应使用新的默认提示和农历备注');
assert.match(source, /function calendarStatData[\s\S]{0,1800}holidayRecords[\s\S]{0,500}solarRecords[\s\S]{0,500}memorialRecords[\s\S]{0,500}birthdayRecords/, '统计方块应按节日优先级组合标题和备注');
assert.match(source, /\.calendar-stat \.stat-name\s*\{[^}]*font-size:\s*9px[^}]*font-weight:\s*400/, '节气、生日等备注应使用与农历日期相同的低强调字体');
assert.match(source, /\{ title: calendarStatNames\(holidayRecords\.length \? holidayRecords : solarRecords\), note: holidayRecords\.length && solarRecords\.length \? calendarStatNames\(solarRecords\) : '节气节日' \}/, '无节日数据时默认提示应作为备注显示');
assert.match(source, /\{ title: calendarStatNames\(memorialRecords\.length \? memorialRecords : birthdayRecords\), note: memorialRecords\.length && birthdayRecords\.length \? calendarStatNames\(birthdayRecords\) : '纪念日 生日' \}/, '无纪念日数据时默认提示应作为备注显示');
assert.match(source, /\{ title: calendarStatNames\(specialRecords\), note: calendarStatNames\(specialRecords\) \? '' : '特殊日' \}/, '无特殊日数据时默认提示应作为备注显示');
assert.match(source, /sectionAddButton'\)\.addEventListener\('click', function\(\) \{ pageType === 'calendar' \? openCalendarAddEditor\(\) : openEditor\(null\); \}\)/, '日历序列加号应打开专用新增记录弹窗');
assert.match(source, /function calendarRecordName[\s\S]{0,420}record\.time[\s\S]{0,220}return Number\(dateValue\[2\]\) \+ '\.' \+ Number\(dateValue\[3\]\)/, '手动日历记录应显示月日和名称');
assert.match(source, /id="calendarAddModal"[\s\S]{0,900}id="calendarAddDateInput"[\s\S]{0,300}id="calendarAddNameInput"[\s\S]{0,500}id="calendarAddCancelButton"[\s\S]{0,180}id="calendarAddSaveButton"/, '日历加号应使用仅含日期、名称和取消保存按钮的小弹窗');
assert.match(source, /function openCalendarAddEditor[\s\S]{0,500}calendarAddModal[\s\S]{0,160}calendarAddDateInput/, '日历加号应打开专用新增弹窗');
assert.match(source, /sectionAddButton'\)\.addEventListener\('click', function\(\) \{ pageType === 'calendar' \? openCalendarAddEditor\(\) : openEditor\(null\); \}\)/, '日历加号不应打开通用记录弹窗');
assert.match(source, /id="itemActionModal"[\s\S]{0,700}id="itemActionNameInput"[\s\S]{0,500}id="itemActionDeleteButton"[\s\S]{0,260}id="itemActionSaveButton"/, '项目双击应打开仅含重命名和删除的小操作框');
assert.match(source, /item\.addEventListener\('dblclick'[\s\S]{0,180}openItemActionEditor\(record\.id\)/, '项目方块应支持双击操作');
assert.match(source, /function openItemActionEditor[\s\S]{0,500}itemActionModal[\s\S]{0,160}itemActionNameInput/, '双击应打开项目操作框');
assert.match(source, /itemActionDeleteButton[\s\S]{0,900}removeFromNewStats\(itemActionId\)/, '删除项目时应清理统计引用');
assert.match(source, /else \{ categoryNames\.push\(name\); currentCategory = name; calendarCategoryRoles\[name\] = pageType === 'calendar' \? 'custom' : '';/, '新增序列应保存自定义分类标识');
assert.match(source, /categorySaveButton'\)[\s\S]{0,260}if \(!name\) return;/, '序列保存不应引用项目日期变量');
assert.match(source, /function refreshCalendarHolidayYear[\s\S]{0,500}fetch\(['"]https:\/\/timor\.tech\/api\/holiday\/year\//, '进入新年份时应尝试获取节日数据');
assert.match(source, /function refreshCalendarHolidayYear[\s\S]{0,1200}localStorage\.setItem\(['"]personal-life-hub-calendar-annual-v1/, '获取到的年度节日数据应缓存到本地');
assert.match(source, /refreshCalendarHolidayYear\(new Date\(\)\.getFullYear\(\)\)/, '页面启动时应刷新当前年度节日数据');
assert.doesNotMatch(source, /function ensureCalendarHolidayPlaceholders/, '重要节日不应再预置空白方块');
assert.doesNotMatch(source, /personal-life-holiday-placeholders-deleted-v1/, '删除项目不应再维护空白方块删除状态');
assert.doesNotMatch(source, /itemActionDeleteButton[\s\S]{0,500}\[5191, 5192\]/, '项目删除逻辑不应再特殊处理预置空白方块');
assert.match(source, /function loadState[\s\S]{0,500}records = records\.filter\(function\(record\) \{ return \[5191, 5192\]\.indexOf\(record\.id\) === -1; \}\)/, '加载时应清理历史遗留的预置空白方块');
assert.match(source, /function loadState[\s\S]{0,700}return !\(pageType === 'calendar' && !record\.name && record\.time\)/, '加载时应清理只有日期没有名称的灰色方块');
assert.match(source, /var name = document\.getElementById\('calendarAddNameInput'\)\.value\.trim\(\);[\s\S]{0,220}time = name \? time : ''/, '新增空白方块不应保留单独日期');
assert.doesNotMatch(source, /item\.addEventListener\('click'[\s\S]{0,180}openEditor\(record\.id\)/, '单击项目方块不应打开编辑框');
assert.doesNotMatch(source, /calendarAddSaveButton'[\s\S]{0,500}if \(!time \|\| !name\) return/, '新增日历方块不应强制填写日期和名称');
assert.match(source, /function refreshCalendarHolidayYear[\s\S]{0,1400}if \(record && !annualDates\[record\.id\]\) annualDates\[record\.id\] = holiday\.date/, '接口节假日放假起始日不应覆盖已有准确节日日期');
assert.match(source, /calendarHolidayAnnualDates\[year\] = Object\.assign\(\{\}, cached\[year\][\s\S]{0,120}calendarHolidayAnnualDates\[year\]/, '本地缓存不应覆盖内置的准确年度日期');
assert.match(source, /function ensureCalendarSolarTerms[\s\S]{0,700}personal-life-calendar-deleted-v1/, '内置日历记录删除状态应持久化');
assert.match(source, /itemActionDeleteButton[\s\S]{0,900}personal-life-calendar-deleted-v1/, '删除内置日历记录时应记录删除状态');

console.log('节日节气页面行为约束通过');
