const fs = require('fs');
const assert = require('assert');

const source = fs.readFileSync(__dirname + '/wood-kitchen-template.html', 'utf8');
const lifeSource = fs.readFileSync(__dirname + '/wood-life-timeline.html', 'utf8');
const renameSource = fs.readFileSync(__dirname + '/wood-rename.html', 'utf8');

assert.match(source, /statAssignments\s*=\s*\{\s*new:\s*\[\]/, '统计状态应包含本月新增集合');
assert.doesNotMatch(source, /if \(\['new', 'discarded', 'need'\][\s\S]{0,120}push\(dragId\)/, '本月新增不能通过拖动计数');
assert.doesNotMatch(source, /key === 'new'[\s\S]{0,220}statAssignments\.new\.indexOf/, '本月新增不能依赖拖动集合');
assert.match(source, /id="addCategoryButton"/, '左侧应有新增分类加号按钮');
assert.match(source, /function renameCategory/, '分类应支持重命名');
assert.match(source, /function deleteCategory/, '分类应支持删除');
assert.match(source, /button\.addEventListener\('dblclick'[\s\S]{0,180}openCategoryEditor\(name\)/, '序列应通过双击打开编辑窗口');
assert.match(source, /id="categoryNameInput"/, '序列编辑窗口应包含重命名输入框');
assert.match(source, /id="categoryDeleteButton"[\s\S]{0,100}id="categoryCancelButton"[\s\S]{0,100}id="categorySaveButton"/, '序列编辑窗口底部应依次提供删除、取消、保存');
assert.match(source, /categoryDeleteButton'\)\.addEventListener\('click'[\s\S]{0,180}deleteCategory\(editingCategory\)/, '删除按钮应删除当前序列');
assert.doesNotMatch(source, /button\.addEventListener\('click'[\s\S]{0,180}renderCategories\(\)[\s\S]{0,80}render\(\)/, '序列单击不应在双击完成前替换按钮节点');
assert.match(source, /currentCategory = name;[\s\S]{0,300}render\(true\)/, '序列单击应保留按钮节点以支持双击重命名');
assert.match(source, /currentCategory = name;\s*saveState\(\);/, '序列单击后应立即保存当前分类以便刷新恢复');
assert.match(source, /\.good-habit-page \.sleep-table\.leave-table th:first-child,\s*\n\s*\.good-habit-page \.sleep-table\.leave-table td:first-child,\s*\n\s*\.good-habit-page \.sleep-table\.leave-table th:nth-child\(2\),\s*\n\s*\.good-habit-page \.sleep-table\.leave-table td:nth-child\(2\)\s*\{\s*width: 41px; padding-left: 4px; padding-right: 4px; \}/, '休假表日期与休假日列应等宽且同内边距');
assert.match(source, /\.good-habit-page \.leave-table-split \.leave-table \{ flex-shrink: 0; \}/, '休假表不得被 flex 压缩以保持日期与休假日列等宽');
assert.match(source, /\.good-habit-page \.leave-table-split \{[^}]*overflow-x: auto/, '休假表并排容器应横向可滚动以免列宽被挤压');
assert.match(source, /function openCategoryEditor[\s\S]{0,700}categoryNameInput/, '序列重命名应在编辑窗口显示输入框');
assert.doesNotMatch(source, /if \(pageType !== 'kitchen' && pageType !== 'bath'\) return;/, '所有记录子主题都应允许编辑序列');
assert.doesNotMatch(source, /pageType === 'kitchen' && Array\.isArray\(saved\.categories\)/, '所有记录页面都应恢复保存的左侧序列');
assert.match(source, /id="dailyMealInput"/, '每日餐食应使用单一记录输入框');
assert.match(source, /currentCategory === '每日餐食'/, '每日餐食应使用专用编辑界面');
assert.match(source, /function setEditorExpanded/, '编辑框应支持展开和缩小');
assert.match(source, /id="expandButton"/, '编辑框应提供展开按钮');
assert.match(source, /\.record-editor\.expanded[\s\S]{0,240}\.regular-record-fields:not\(\[hidden\]\), \.record-editor\.expanded \.daily-meal-fields:not\(\[hidden\]\)[\s\S]{0,160}display: flex/, '展开编辑框时输入区父容器应填满高度');
assert.match(source, /\.record-editor\.expanded \.regular-record-fields:not\(\[hidden\]\), \.record-editor\.expanded \.daily-meal-fields:not\(\[hidden\]\)/, '每日餐食展开时仍应只显示一个记录框');
assert.match(source, /dailyMealInput[\s\S]{0,800}records\.push|dailyMealInput[\s\S]{0,800}editingRecord\.name/, '每日餐食记录应保存输入内容');
assert.match(lifeSource, /\.timeline \{[\s\S]{0,180}overflow-y: auto[\s\S]{0,180}scrollbar-width: none[\s\S]{0,180}-ms-overflow-style: none/, '人生进度应保留滚动并隐藏滚动条');
assert.match(lifeSource, /\.editor textarea \{[\s\S]{0,220}scrollbar-width: none[\s\S]{0,220}-ms-overflow-style: none/, '成长记录编辑框应隐藏滚动条并保留滚动');
assert.match(renameSource, /id="subEditorModal"/, '子主题应使用独立编辑窗口');
assert.match(renameSource, /id="subEditorDeleteButton"[\s\S]{0,220}id="subEditorCancelButton"[\s\S]{0,220}id="subEditorSaveButton"/, '子主题编辑窗口应提供删除、取消、保存按钮');
assert.match(renameSource, /function deleteSubTheme\(\)[\s\S]{0,180}if \(!subEditingLabel\)[\s\S]{0,100}closeSubEditor/, '新增主题点击删除应直接关闭且不创建方块');
assert.doesNotMatch(renameSource, /subEditorDeleteButton'\)\.hidden = !label/, '新增主题编辑窗口左侧删除按钮不能隐藏');
assert.match(renameSource, /function openSubEditor/, '子主题应支持打开编辑窗口');
assert.match(renameSource, /function deleteSubTheme/, '子主题应支持直接删除');
assert.match(renameSource, /add-sub-button|新增主题/, '母主题下方应提供新增主题入口');
assert.match(renameSource, /bar\.addEventListener\('dblclick'[\s\S]{0,300}openSubEditor/, '子主题双击应打开编辑窗口');
assert.match(renameSource, /function addSubTheme\(cell\)\s*\{[\s\S]{0,180}openSubEditor\(null, cell\.id\)/, '点击新增主题时应先打开编辑框而不是立即创建方块');
assert.match(renameSource, /else if \(subAddingCell\)[\s\S]{0,180}createSubBar\(subAddingCell\)/, '只有保存新增主题时才创建新的子主题方块');
assert.doesNotMatch(renameSource, /function addSubTheme\(cell\)[\s\S]{0,220}find\(function\(bar\)/, '新增子主题不能复用前面的空白方块');
assert.match(renameSource, /function openGenericSubTemplate/, '未配置专用页面的子主题也应支持单击进入项目界面');
assert.match(renameSource, /cell3[\s\S]{0,260}firstElementChild[\s\S]{0,120}habit=1/, 'Action 当前第一个子主题跳转应携带专用页面标记');
assert.match(source, /queryParams\.get\('habit'\) === '1'/, '模板应依据好习惯追踪专用页面标记识别页面');
assert.match(renameSource, /function navigateWithWoodClick\(url\)[\s\S]{0,180}clickTimer = setTimeout/, '单击进入的跳转应可被双击编辑取消');
assert.doesNotMatch(renameSource, /class="sub-bar[^>]*onclick=/, '子主题不能使用会抢先跳转的内联单击事件');
assert.match(renameSource, /list\.appendChild\(addButton\)/, '新增主题按钮应与子主题保持在同一底色容器内');
assert.match(renameSource, /loadState\(\);[\s\S]{0,500}placeAddSubButton\(list\)/, '状态恢复后新增主题按钮仍应位于子主题列表底部');
assert.match(renameSource, /function placeAddSubButton[\s\S]{0,160}list\.appendChild\(addButton\)/, '新增主题按钮应始终放在子主题列表末尾');
assert.match(renameSource, /addButton\.addEventListener\('click'[\s\S]{0,180}list\.appendChild\(addButton\)/, '新增主题按钮创建后必须插入子主题列表');
assert.match(renameSource, /\.add-sub-button\s*\{[^}]*order:\s*999/, '新增主题按钮应通过布局顺序固定在底部');
assert.match(renameSource, /loadState\(\);[\s\S]{0,500}placeAddSubButton\(list\)/, '恢复状态后应重新将新增主题按钮放到列表末尾');
assert.doesNotMatch(source, /var hasSavedState = loadState\(\);[\s\S]{0,120}if \(!hasSavedState\) saveState\(\);/, '页面初始化不能自动写入默认数据');
assert.match(source, /function saveState\(\)[\s\S]{0,500}localStorage\.setItem\(storageKey/, '统计快照异常时仍应执行本地存储写入');
assert.match(source, /currentCategory: currentCategory/, '保存记录时应同步保存当前分类');
assert.match(source, /saved\.currentCategory[\s\S]{0,100}currentCategory = saved\.currentCategory/, '刷新后应恢复上次打开的分类');
assert.match(source, /queryParams\.get\('habit'\) === '1'[\s\S]{0,140}savedReturnTitle === '好习惯追踪'[\s\S]{0,100}customTitle === '好习惯追踪'/, '好习惯追踪页面应按专用标记或名称识别');
assert.match(source, /id="sleepTablePanel"/, '好习惯追踪页面应包含睡眠检测表容器');
assert.match(source, /睡眠时间段|8:00前|8:00-9:00|9:00后|23:00前|23:00-24:00|24:00后/, '睡眠检测表应包含指定时间段');
assert.match(source, /function toggleSleepCheck[\s\S]{0,260}saveState\(\)/, '睡眠时间段点击后应保存圆点状态');
assert.doesNotMatch(source, /for \(var day = 1; day <= days; day\+\+\)/, '睡眠表循环不能用 var，否则点击闭包会共享 day 导致无法交互');
assert.match(source, /for \(let day = 1; day <= days; day\+\+\)/, '睡眠表循环应用 let 绑定每天的点击闭包');
assert.match(source, /var isActionGoodHabitPage = queryParams\.get\('habit'\) === '1' \|\| returnSub === 'cell3-sub-1790089557201-1'/, '只有 Action 当前第一个子主题入口应触发专用按钮逻辑');
assert.match(source, /personal-life-hub-custom-cell3-sub-1790089557201-1-v1/, '应按导出数据中的好习惯追踪存储键识别页面');
assert.match(source, /action-good-habit-page/, '好习惯追踪页面应有专用样式标记');
assert.match(source, /\.good-habit-page \.sleep-table-panel \{ margin-top: -10px;? \}/, '睡眠检测表应整体上移20px');
assert.match(source, /function isSleepStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'sleep'; \}/, '睡眠序列判定应按序列身份而非数组下标');
assert.match(source, /function statTitle\(stat\)[\s\S]{0,200}isSleepStatSequence\(\)[\s\S]{0,80}睡眠时长(?!总)/, '睡眠序列第一方块标题应为睡眠时长');
assert.doesNotMatch(source, /睡眠总时长/, '第一方块简介不应带“总”字');
assert.match(source, /function countFor\(key\)[\s\S]{0,200}isSleepStatSequence\(\)[\s\S]{0,80}sleepDurationText\(\)/, '睡眠序列第一方块计数应来自睡眠总时长');
assert.match(source, /function sleepPeriodMinutes\(period\)[\s\S]{0,700}480[\s\S]{0,200}510[\s\S]{0,200}540[\s\S]{0,400}1380[\s\S]{0,200}1410[\s\S]{0,200}1440/, '六个时间段应映射为 8:00/8:30/9:00/23:00/23:30/24:00 分钟数');
assert.match(source, /function sleepDurationText\(\)[\s\S]{0,700}return '--'/, '缺一侧数据时应显示 --');
assert.match(source, /function sleepDurationText\(\)[\s\S]{0,900}\+ 'h'/, '时长应以 h 结尾（如 8.5h）');
assert.match(source, /duration <= 0[\s\S]{0,80}duration \+= 24 \* 60/, '入睡到起床跨零点应补 24 小时');
assert.match(source, /function toggleSleepCheck[\s\S]{0,400}updateSleepStatCards\(\)/, '勾选睡眠时间段后应刷新统计方块');
assert.match(source, /function statTitle\(stat\)[\s\S]{0,800}咸鱼翻身/, '第二方块标题应为咸鱼翻身');
assert.match(source, /function statTitle\(stat\)[\s\S]{0,800}咸鱼日常/, '第三方块标题应为咸鱼日常');
assert.match(source, /function statTitle\(stat\)[\s\S]{0,800}烂命一条/, '第四方块标题应为烂命一条');
assert.match(source, /new: \['8:00前', '23:00前'\]/, '咸鱼翻身应统计8点前起床和11点前睡觉');
assert.match(source, /discarded: \['8:00-9:00', '23:00-24:00'\]/, '咸鱼日常应统计8-9点起床和11-24点睡觉');
assert.match(source, /need: \['9:00后', '24:00后'\]/, '烂命一条应统计9点后起床和24点后睡觉');
assert.match(source, /function sleepPairCount\(key\)/, '应有区间方块月度累计函数');
assert.match(source, /function countFor\(key\)[\s\S]{0,500}sleepPairCount\(key\)/, '睡眠序列区间方块计数应来自月度累计');
assert.match(source, /function shiftSleepMonth[\s\S]{0,450}updateSleepStatCards\(\)/, '切换表格月份应刷新区间方块');
assert.match(source, /'<thead><tr><th[^>]*>日期<\/th><th[^>]*>时长<\/th>'/, '睡眠表应在日期后增加时长列');
assert.match(source, /function sleepPeriodWidth\(period\)/, '应有时长列表头宽度函数');
assert.match(source, /period\.indexOf\('-'\) !== -1 \? \d+ : \d+/, '时间段标题应比短标题更宽');
assert.match(source, /\.good-habit-page \.sleep-table th \{[^}]*white-space: nowrap/, '表头应保持单行不换行');
assert.match(source, /function sleepDurationTextFor\(dateKey\)/, '应有按日期键计算时长的函数');
assert.match(source, /durationCell\.textContent = sleepDurationTextFor\(/, '每行应渲染当天时长');
assert.match(source, /id="moodTablePanel"/, '应包含情绪检测表容器');
assert.match(source, /moodPeriods = \['开心', '平常', '伤心', '生气', '焦虑'\]/, '情绪表应包含五种情绪');
assert.match(source, /function toggleMoodCheck[\s\S]{0,260}saveState\(\)/, '情绪圆圈点击后应保存');
assert.match(source, /moodTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'mood'/, '情绪表应按序列身份显示，重排后仍跟随');
assert.match(source, /function renderMoodTable\(\)/, '应有情绪表渲染函数');
assert.match(source, /function renderMoodTable[\s\S]{0,800}情绪检测表/, '情绪表标题应为情绪检测表');
assert.match(source, /table\.className = 'sleep-table mood-table'/, '情绪表应附加 mood-table 类以区分列宽规则');
assert.match(source, /\.good-habit-page \.mood-table \{[^}]*width: auto;[^}]*min-width: 0;[^}]*\}|\.good-habit-page \.mood-table \{[^}]*min-width: 0;[^}]*width: auto;[^}]*\}/, '情绪表宽度应自适应内容以收窄到一屏展示');
assert.match(source, /\.good-habit-page \.mood-table th, \.good-habit-page \.mood-table td \{ width: \d+px; \}/, '情绪表各列应固定为紧凑宽度');
assert.doesNotMatch(source, /\.good-habit-page \.mood-table th:nth-child\(2\)[^}]*width: auto/, '情绪表第二列不应为 auto（须覆盖睡眠表36px规则）');
assert.match(source, /function isMoodStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'mood'; \}/, '情绪序列判定应按序列身份而非数组下标');
assert.match(source, /function statTitle\(stat\)[\s\S]{0,300}闲鱼开心日/, '情绪序列第一方块标题应为闲鱼开心日');
assert.match(source, /if \(isMoodStatSequence\(\)\) \{[\s\S]{0,240}'伤心'[\s\S]{0,120}'生气'[\s\S]{0,120}'焦虑'/, '情绪序列第2-4方块标题应为伤心/生气/焦虑');
assert.match(source, /function moodCount\(key\)/, '应有情绪月度累计函数');
assert.match(source, /total: \['开心', '平常'\]/, '第一方块应把开心和平常合并为每天计1');
assert.match(source, /function countFor\(key\)[\s\S]{0,300}isMoodStatSequence\(\)[\s\S]{0,60}moodCount\(key\)/, '情绪序列方块计数应来自月度累计');
assert.match(source, /function toggleMoodCheck[\s\S]{0,400}updateSleepStatCards\(\)/, '勾选情绪后应刷新统计方块');
assert.match(source, /moodChecks\[moodCheckKey\(day, mood\)\]/, '情绪圆圈应读取勾选状态');
assert.match(source, /state\.moodChecks = moodChecks/, '情绪勾选应持久化到存储');
assert.match(source, /saved\.moodChecks/, '加载时应恢复情绪勾选');
assert.match(source, /function shiftSleepMonth[\s\S]{0,300}renderMoodTable\(\)/, '切换月份应同步刷新情绪表');
assert.match(source, /renderSleepTable\(\);\s*\n\s*renderMoodTable\(\);\s*\n\s*renderDietTable\(\);\s*\n\s*renderExerciseTable\(\);\s*\n\s*renderWeightTable\(\);\s*\n\s*renderLearnTable\(\);\s*\n\s*renderLoveTable\(\);\s*\n\s*renderLeaveTable\(\);\s*\n\s*renderBadHabitTable\(\);\s*\n\s*\}/, 'render 应调用坏习惯表渲染');
assert.match(source, /\.good-habit-page #moodTablePanel \{ margin-left: 5px;? \}/, '情绪检测表应整体向右移动5px');
assert.match(source, /\.good-habit-page \.mood-table th:first-child, \.good-habit-page \.mood-table td:first-child \{ width: 40px;/, '情绪表日期列宽度应与情绪列一致');
assert.match(source, /\.good-habit-page \.mood-table th:first-child, \.good-habit-page \.mood-table td:first-child \{[^}]*padding-left: 4px/, '日期列左侧宽度应再增加3px（1px基础+3px）');
assert.match(source, /\.good-habit-page \.mood-table th:last-child, \.good-habit-page \.mood-table td:last-child \{[^}]*padding-right: 4px/, '末列情绪右侧宽度应再增加3px（1px基础+3px）');
assert.match(source, /\.good-habit-page \.mood-table th:nth-child\(2\)[\s\S]{0,400}th:nth-child\(5\)[\s\S]{0,200}td:nth-child\(5\)[^}]*width: 43px/, '中间四个情绪列宽度应各增加3px（40→43px）');
assert.match(source, /id="dietTablePanel"/, '应包含饮食记录表容器');
assert.match(source, /dietMeals = \['早餐', '中餐', '晚餐', '加餐\/零食'\]/, '饮食表应包含三餐与加餐/零食标题');
assert.match(source, /function dietCheckKey\(day, meal\)/, '应有饮食状态键函数');
assert.match(source, /dietTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'diet'/, '饮食表应按序列身份显示，重排后仍跟随');
assert.match(source, /function toggleDietCheck[\s\S]{0,300}saveState\(\)/, '饮食点击后应保存状态');
assert.match(source, /function toggleDietCheck[\s\S]{0,400}renderDietTable\(\)/, '点击饮食格后应刷新饮食表');
assert.match(source, /function renderDietTable\(\)/, '应有饮食表渲染函数');
assert.match(source, /function renderDietTable[\s\S]{0,800}饮食记录表/, '饮食表标题应为饮食记录表');
assert.match(source, /table\.className = 'sleep-table diet-table'/, '饮食表应附加 diet-table 类');
assert.match(source, /function nextDietState[\s\S]{0,200}'light'[\s\S]{0,120}'heavy'[\s\S]{0,80}return ''/, '三餐应循环切换没吃→清淡→重油→没吃');
assert.match(source, /function nextDietState[\s\S]{0,200}加餐\/零食[\s\S]{0,80}eaten/, '零食应在空心与实心间切换');
assert.match(source, /dietChecks\[dietCheckKey\(day, meal\)\]/, '饮食格应读取已保存状态');
assert.match(source, /state\.dietChecks = dietChecks/, '饮食状态应持久化到存储');
assert.match(source, /saved\.dietChecks/, '加载时应恢复饮食状态');
assert.match(source, /function shiftSleepMonth[\s\S]{0,400}renderDietTable\(\)/, '切换月份应同步刷新饮食表');
assert.match(source, /\.good-habit-page \.sleep-dot\.diet-light \{ background: #4a9a52/, '清淡饮食应显示为绿色按钮');
assert.match(source, /\.good-habit-page \.sleep-dot\.diet-heavy \{ background: #c0504a/, '重油重盐应显示为红色按钮');
assert.match(source, /\.good-habit-page \.sleep-dot\.diet-eaten \{ background: #806b52/, '零食勾选应显示为实心圆');
assert.match(source, /\.good-habit-page \.sleep-table\.diet-table th, \.good-habit-page \.sleep-table\.diet-table td \{ width: 50px; \}/, '饮食表中间列宽应为50px（46+4）');
assert.match(source, /\.good-habit-page \.sleep-table\.diet-table th:first-child, \.good-habit-page \.sleep-table\.diet-table td:first-child \{ width: 44px;/, '饮食表日期列宽应为44px（40+4）');
assert.match(source, /\.good-habit-page \.sleep-table\.diet-table th:last-child, \.good-habit-page \.sleep-table\.diet-table td:last-child \{ width: 60px;/, '饮食表末列宽应为60px（56+4）');
assert.match(source, /function isDietStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'diet'; \}/, '饮食序列判定应按序列身份而非数组下标');
assert.match(source, /if \(stat\.key === 'total' && isDietStatSequence\(\)\) return '清淡饮食';/, '饮食序列第一方块标题应为清淡饮食');
assert.match(source, /if \(isDietStatSequence\(\)\) \{[\s\S]{0,240}'重油重盐'[\s\S]{0,120}'未吃次数'[\s\S]{0,120}'零食次数'/, '饮食序列第2-4方块标题应为重油重盐/未吃次数/零食次数');
assert.match(source, /function dietCount\(key\)/, '应有饮食月度累计函数');
assert.match(source, /function countFor\(key\)[\s\S]{0,400}isDietStatSequence\(\)[\s\S]{0,60}dietCount\(key\)/, '饮食序列方块计数应来自月度累计');
assert.match(source, /function toggleDietCheck[\s\S]{0,400}updateSleepStatCards\(\)/, '点击饮食格后应刷新统计方块');
assert.match(source, /function dietCount\(key\)[\s\S]{0,650}value === 'light'/, '清淡饮食应统计三餐绿色状态');
assert.match(source, /function dietCount\(key\)[\s\S]{0,800}value === 'heavy'/, '重油重盐应统计三餐红色状态');
assert.match(source, /function dietCount\(key\)[\s\S]{0,950}key === 'discarded' && !value/, '未吃次数应统计三餐空心状态');
assert.match(source, /function dietCount\(key\)[\s\S]{0,600}加餐\/零食[^\n]{0,90}=== 'eaten'/, '零食次数应只统计加餐/零食实心');
assert.match(source, /id="exerciseTablePanel"/, '应包含运动记录表容器');
assert.match(source, /function exerciseCheckKey\(day\)/, '应有运动日期键函数');
assert.match(source, /exerciseTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'exercise'/, '运动表应按序列身份显示，重排后仍跟随');
assert.match(source, /function toggleExerciseCheck[\s\S]{0,300}saveState\(\)/, '运动圆圈点击后应保存');
assert.match(source, /function toggleExerciseCheck[\s\S]{0,400}renderExerciseTable\(\)/, '点击运动格后应刷新运动表');
assert.match(source, /function toggleExerciseCheck[\s\S]{0,500}updateSleepStatCards\(\)/, '勾选运动后应刷新统计方块');
assert.match(source, /function renderExerciseTable\(\)/, '应有运动表渲染函数');
assert.match(source, /function renderExerciseTable[\s\S]{0,800}运动记录表/, '运动表标题应为运动记录表');
assert.match(source, /table\.className = 'sleep-table exercise-table'/, '运动表应附加 exercise-table 类');
assert.match(source, /<th>是否运动<\/th><th>运动时长<\/th><th>运动方式<\/th>/, '运动表应包含三列表头');
assert.match(source, /exerciseChecks\[exerciseCheckKey\(day\)\]/, '运动圆圈应读取已保存状态');
assert.match(source, /state\.exerciseChecks = exerciseChecks/, '运动勾选应持久化到存储');
assert.match(source, /saved\.exerciseChecks/, '加载时应恢复运动勾选');
assert.match(source, /state\.exerciseDurations = exerciseDurations/, '运动时长应持久化到存储');
assert.match(source, /saved\.exerciseDurations/, '加载时应恢复运动时长');
assert.match(source, /state\.exerciseMethods = exerciseMethods/, '运动方式应持久化到存储');
assert.match(source, /saved\.exerciseMethods/, '加载时应恢复运动方式');
assert.match(source, /function shiftSleepMonth[\s\S]{0,500}renderExerciseTable\(\)/, '切换月份应同步刷新运动表');
assert.match(source, /renderDietTable\(\);\s*\n\s*renderExerciseTable\(\)/, 'render 应调用运动表渲染');
assert.match(source, /exercise-cell-input/, '时长与方式应为格内直接输入框');
assert.match(source, /addEventListener\('input'[\s\S]{0,300}setExerciseField/, '输入时应实时保存并刷新方块');
assert.match(source, /function isExerciseStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'exercise'; \}/, '运动序列判定应按序列身份而非数组下标');
assert.match(source, /if \(isExerciseStatSequence\(\)\) \{[\s\S]{0,140}'运动总时长'[\s\S]{0,140}'最常坚持'[\s\S]{0,140}'最难坚持'/, '运动序列第2-4方块标题应为运动总时长/最常坚持/最难坚持');
assert.match(source, /function exerciseCount\(key\)/, '应有运动月度累计函数');
assert.match(source, /function countFor\(key\)[\s\S]{0,550}isExerciseStatSequence\(\)[\s\S]{0,60}exerciseCount\(key\)/, '运动序列方块计数应来自月度累计');
assert.match(source, /function exerciseCount\(key\)[\s\S]{0,500}exerciseChecks\[/, '运动总数应统计实心圆天数');
assert.match(source, /function exerciseCount\(key\)[\s\S]{0,800}exerciseDurations/, '运动总时长应累计时长输入');
assert.match(source, /function exerciseCount\(key\)[\s\S]{0,1100}exerciseMethods/, '最常最难坚持应统计方式输入');
assert.match(source, /function exerciseCount\(key\)[\s\S]{0,1400}if \(key === 'discarded'\)[\s\S]{0,250}counts/, '最常坚持应取出现次数最多');
assert.match(source, /function exerciseCount\(key\)[\s\S]{0,1600}if \(key === 'need'\)[\s\S]{0,250}counts/, '最难坚持应取出现次数最少');
assert.match(source, /function exerciseCount\(key\)[\s\S]{0,1800}return ''/, '无运动方式记录时方块应留白');
assert.match(source, /\.good-habit-page \.sleep-table\.exercise-table \{ width: auto; min-width: 0; \}/, '运动表宽度应自适应以收窄到一屏');
assert.match(source, /\.good-habit-page \.sleep-table\.exercise-table th:first-child[^}]*width: 44px;/, '运动表日期列宽应为44px');
assert.match(source, /\.good-habit-page \.exercise-cell-input \{[^}]*border: 0/, '运动输入格应无边框嵌入单元格');
assert.match(source, /\.good-habit-page \.sleep-table\.exercise-table th \{[^}]*font-size: 1[12]px/, '运动表头字体应略大于默认9px');
assert.match(source, /\.good-habit-page \.sleep-table\.exercise-table th \{[^}]*letter-spacing:/, '运动表头字间应留空隙');
assert.match(source, /function exerciseCount\(key\)[\s\S]{0,2000}counts\[name\] === (max|min)[\s\S]{0,120}join\(/, '并列最多或最少时应全部拼接显示');
assert.match(source, /\.stat-count\.compact \{[^}]*font-size:\s*1[0-3]px/, '并列方式过多时应缩小方块数字字号');
assert.match(source, /updateSleepStatCards[\s\S]{0,500}classList\.toggle\('compact'/, '刷新方块时应按内容切换紧凑字号');
assert.match(source, /card\.dataset\.key = stat\.key;[\s\S]{0,400}classList\.toggle\('compact'/, '初始渲染方块时应按内容切换紧凑字号');
assert.match(source, /id="weightTablePanel"/, '应包含体重记录表容器');
assert.match(source, /weightTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'weight'/, '体重表应按序列身份显示，重排后仍跟随');
assert.match(source, /function renderWeightTable\(\)/, '应有体重表渲染函数');
assert.match(source, /function renderWeightTable[\s\S]{0,800}体重记录表/, '体重表标题应为体重记录表');
assert.match(source, /table\.className = 'sleep-table weight-table'/, '体重表应附加 weight-table 类');
assert.match(source, /<th>空腹体重<\/th><th>备注<\/th>/, '体重表应包含空腹体重与备注表头');
assert.match(source, /state\.weightValues = weightValues/, '空腹体重应持久化到存储');
assert.match(source, /saved\.weightValues/, '加载时应恢复空腹体重');
assert.match(source, /state\.weightNotes = weightNotes/, '体重备注应持久化到存储');
assert.match(source, /saved\.weightNotes/, '加载时应恢复体重备注');
assert.match(source, /function setWeightField[\s\S]{0,400}saveState\(\)/, '体重格输入后应保存');
assert.match(source, /function setWeightField[\s\S]{0,500}updateSleepStatCards\(\)/, '体重格输入后应刷新统计方块');
assert.match(source, /addEventListener\('input'[\s\S]{0,300}setWeightField/, '体重与时长应为格内直接输入框');
assert.match(source, /function shiftSleepMonth[\s\S]{0,600}renderWeightTable\(\)/, '切换月份应同步刷新体重表');
assert.match(source, /renderExerciseTable\(\);\s*\n\s*renderWeightTable\(\);\s*\n\s*renderLearnTable\(\);\s*\n\s*renderLoveTable\(\);\s*\n\s*renderLeaveTable\(\);\s*\n\s*renderBadHabitTable\(\);\s*\n\s*\}/, 'render 应调用坏习惯表渲染');
assert.match(source, /\.good-habit-page \.sleep-table\.weight-table \{ width: auto; min-width: 0; \}/, '体重表宽度应自适应以收窄到一屏');
assert.match(source, /\.good-habit-page \.sleep-table\.weight-table th:first-child[^}]*width: 44px;/, '体重表日期列宽应为44px');
assert.match(source, /\.good-habit-page \.weight-cell-input \{[^}]*border: 0/, '体重输入格应无边框嵌入单元格');
assert.match(source, /\.good-habit-page \.sleep-table\.weight-table th \{[^}]*font-size: 1[12]px/, '体重表头字体应略大于默认9px');
assert.match(source, /\.good-habit-page \.sleep-table\.weight-table th \{[^}]*letter-spacing:/, '体重表头字间应留空隙');
assert.match(source, /function isWeightStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'weight'; \}/, '体重序列判定应按序列身份而非数组下标');
assert.match(source, /if \(isWeightStatSequence\(\)\) \{[\s\S]{0,200}'记录天数'[\s\S]{0,200}'平均体重'[\s\S]{0,200}'最低体重'[\s\S]{0,200}'最重体重'/, '体重序列四个方块标题应为记录天数/平均体重/最低体重/最重体重');
assert.match(source, /function countFor\(key\)[\s\S]{0,700}isWeightStatSequence\(\)[\s\S]{0,60}weightCount\(key\)/, '体重序列方块计数应来自月度统计');
assert.match(source, /function weightCount\(key\)/, '应有体重月度统计函数');
assert.match(source, /function weightCount\(key\)[\s\S]{0,900}weightValues\[/, '体重统计应读取空腹体重数据');
assert.match(source, /function weightCount\(key\)[\s\S]{0,1200}key === 'total'/, '记录天数应统计有体重的天数');
assert.match(source, /function weightCount\(key\)[\s\S]{0,1600}key === 'new'[\s\S]{0,300}(sum|total) \/ ?count/, '平均体重应为总和除以天数');
assert.match(source, /function weightCount\(key\)[\s\S]{0,2000}key === 'discarded'[\s\S]{0,300}Math\.min/, '最低体重应取最小值');
assert.match(source, /function weightCount\(key\)[\s\S]{0,2400}key === 'need'[\s\S]{0,300}Math\.max/, '最重体重应取最大值');
assert.match(source, /function weightCount\(key\)[\s\S]{0,600}return ''/, '无体重记录时方块应留白');
assert.match(source, /id="learnTablePanel"/, '应包含学习记录表容器');
assert.match(source, /learnTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'learn'/, '学习表应按序列身份显示，重排后仍跟随');
assert.match(source, /function learnCheckKey\(day, field\)/, '应有学习日期键函数');
assert.match(source, /function toggleLearnCheck[\s\S]{0,300}saveState\(\)/, '学习圆圈点击后应保存');
assert.match(source, /function toggleLearnCheck[\s\S]{0,400}renderLearnTable\(\)/, '点击学习格后应刷新学习表');
assert.match(source, /function renderLearnTable\(\)/, '应有学习表渲染函数');
assert.match(source, /function renderLearnTable[\s\S]{0,800}学习记录表/, '学习表标题应为学习记录表');
assert.match(source, /table\.className = 'sleep-table learn-table'/, '学习表应附加 learn-table 类');
assert.match(source, /<th>技能<\/th><th>画画<\/th><th>练习<\/th><th>其他<\/th>/, '学习表应包含技能/画画/练习/其他表头');
assert.match(source, /learnChecks\[learnCheckKey\(day, field\)\]/, '学习圆圈应读取已保存状态');
assert.match(source, /state\.learnChecks = learnChecks/, '学习勾选应持久化到存储');
assert.match(source, /saved\.learnChecks/, '加载时应恢复学习勾选');
assert.match(source, /state\.learnNotes = learnNotes/, '学习其他备注应持久化到存储');
assert.match(source, /saved\.learnNotes/, '加载时应恢复学习其他备注');
assert.match(source, /function setLearnNote[\s\S]{0,400}saveState\(\)/, '学习其他输入后应保存');
assert.match(source, /addEventListener\('input'[\s\S]{0,300}setLearnNote/, '学习其他应为格内直接输入框');
assert.match(source, /function shiftSleepMonth[\s\S]{0,700}renderLearnTable\(\)/, '切换月份应同步刷新学习表');
assert.match(source, /renderWeightTable\(\);\s*\n\s*renderLearnTable\(\);\s*\n\s*renderLoveTable\(\);\s*\n\s*renderLeaveTable\(\);\s*\n\s*renderBadHabitTable\(\);\s*\n\s*\}/, 'render 应调用坏习惯表渲染');
assert.match(source, /\.good-habit-page \.sleep-table\.learn-table \{ width: auto; min-width: 0; \}/, '学习表宽度应自适应以收窄到一屏');
assert.match(source, /\.good-habit-page \.sleep-table\.learn-table th:first-child[^}]*width: 44px;/, '学习表日期列宽应为44px');
assert.match(source, /\.good-habit-page \.learn-cell-input \{[^}]*border: 0/, '学习输入格应无边框嵌入单元格');
assert.match(source, /\.good-habit-page \.sleep-table\.learn-table th \{[^}]*font-size: 1[12]px/, '学习表头字体应略大于默认9px');
assert.match(source, /\.good-habit-page \.sleep-table\.learn-table th \{[^}]*letter-spacing:/, '学习表头字间应留空隙');
assert.match(source, /isActionGoodHabitPage && categoryNames\.indexOf\('学习'\) === -1\) categoryNames\.push\('学习'\)/, '好习惯追踪应保证左侧第六个学习序列存在');
assert.match(source, /function isLearnStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'learn'; \}/, '学习序列判定应按序列身份而非数组下标');
assert.match(source, /if \(isLearnStatSequence\(\)\) \{[\s\S]{0,200}'技能天数'[\s\S]{0,200}'画画天数'[\s\S]{0,200}'练习天数'[\s\S]{0,200}'其他天数'/, '学习序列四个方块标题应为技能天数/画画天数/练习天数/其他天数');
assert.match(source, /function countFor\(key\)[\s\S]{0,800}isLearnStatSequence\(\)[\s\S]{0,60}learnCount\(key\)/, '学习序列方块计数应来自月度统计');
assert.match(source, /function learnCount\(key\)/, '应有学习月度统计函数');
assert.match(source, /function learnCount\(key\)[\s\S]{0,900}learnChecks\[/, '技能/画画/练习天数应读取勾选状态');
assert.match(source, /function learnCount\(key\)[\s\S]{0,1200}key === 'total'[\s\S]{0,300}learnCheckKey\(day, '技能'\)/, '技能天数应统计技能实心圆');
assert.match(source, /function learnCount\(key\)[\s\S]{0,1600}key === 'new'[\s\S]{0,300}learnCheckKey\(day, '画画'\)/, '画画天数应统计画画实心圆');
assert.match(source, /function learnCount\(key\)[\s\S]{0,2000}key === 'discarded'[\s\S]{0,300}learnCheckKey\(day, '练习'\)/, '练习天数应统计练习实心圆');
assert.match(source, /function learnCount\(key\)[\s\S]{0,2400}key === 'need'[\s\S]{0,400}learnNotes\[/, '其他天数应统计其他备注天数');
assert.match(source, /function toggleLearnCheck[\s\S]{0,500}updateSleepStatCards\(\)/, '勾选学习后应刷新统计方块');
assert.match(source, /function setLearnNote[\s\S]{0,500}updateSleepStatCards\(\)/, '学习其他输入后应刷新统计方块');
assert.match(source, /id="loveTablePanel"/, '应包含爱心记录表容器');
assert.match(source, /loveTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'love'/, '爱心表应按序列身份显示，重排后仍跟随');
assert.match(source, /'爱心': 'love'/, '爱心序列应默认绑定 love 身份');
assert.match(source, /function isLoveStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'love'; \}/, '爱心序列判定应按序列身份而非数组下标');
assert.match(source, /function loveCheckKey\(day, field\)/, '应有爱心日期键函数');
assert.match(source, /function toggleLoveCheck[\s\S]{0,300}saveState\(\)/, '爱心圆圈点击后应保存');
assert.match(source, /function toggleLoveCheck[\s\S]{0,400}renderLoveTable\(\)/, '点击爱心格后应刷新爱心表');
assert.match(source, /function renderLoveTable\(\)/, '应有爱心表渲染函数');
assert.match(source, /function renderLoveTable[\s\S]{0,800}爱心记录表/, '爱心表标题应为爱心记录表');
assert.match(source, /table\.className = 'sleep-table love-table'/, '爱心表应附加 love-table 类');
assert.match(source, /<th>日期<\/th><th>假期<\/th><th>爱心<\/th>/, '爱心表应包含日期/假期/爱心表头');
assert.match(source, /loveChecks\[loveCheckKey\(day, field\)\]/, '爱心圆圈应读取已保存状态');
assert.match(source, /state\.loveChecks = loveChecks/, '爱心勾选应持久化到存储');
assert.match(source, /saved\.loveChecks/, '加载时应恢复爱心勾选');
assert.match(source, /function shiftSleepMonth[\s\S]{0,800}renderLoveTable\(\)/, '切换月份应同步刷新爱心表');
assert.match(source, /renderLearnTable\(\);\s*\n\s*renderLoveTable\(\);\s*\n\s*renderLeaveTable\(\);\s*\n\s*renderBadHabitTable\(\);\s*\n\s*\}/, 'render 应调用坏习惯表渲染');
assert.match(source, /\.good-habit-page \.sleep-table\.love-table \{ width: auto; min-width: 0; \}/, '爱心表宽度应自适应以收窄到一屏');
assert.match(source, /\.good-habit-page \.sleep-table\.love-table th:first-child[^}]*width: 44px;/, '爱心表日期列宽应为44px');
assert.match(source, /function renderLoveTable[\s\S]{0,1600}Math\.min\(15, days\)/, '爱心表左栏应截到15号');
assert.match(source, /function renderLoveTable[\s\S]{0,1600}\[\s*16,\s*days\s*\]|for \(let day = 16; day <= days/, '爱心表右栏应从16号起');
assert.match(source, /function renderLoveTable[\s\S]{0,2000}createElement\('div'\)[\s\S]{0,80}love-tables|love-table-split/, '爱心表应拆为并排容器');
assert.match(source, /\.good-habit-page \.love-table-split \{[^}]*display: flex/, '爱心表并排容器应为 flex 并排');
assert.match(source, /function toggleLoveCheck[\s\S]{0,500}updateSleepStatCards\(\)/, '勾选爱心后应刷新统计方块');
assert.match(source, /if \(isLoveStatSequence\(\)\) \{[\s\S]{0,200}'月假期数'[\s\S]{0,120}'月爱心数'[\s\S]{0,120}'年假期数'[\s\S]{0,120}'年爱心数'/, '爱心序列四个方块标题应为月假期数/月爱心数/年假期数/年爱心数');
assert.match(source, /function countFor\(key\)[\s\S]{0,800}isLoveStatSequence\(\)[\s\S]{0,60}loveCount\(key\)/, '爱心序列方块计数应来自月/年统计');
assert.match(source, /function loveCount\(key\)/, '应有爱心月年统计函数');
assert.match(source, /function loveCount\(key\)[\s\S]{0,600}key === 'total' \|\| key === 'new'[\s\S]{0,300}loveCheckKey\(day, field\)/, '月假期数/月爱心数应统计当月实心圆');
assert.match(source, /function loveCount\(key\)[\s\S]{0,400}key === 'total' \|\| key === 'discarded'\) \? '假期' : '爱心'/, '假期与爱心字段应按方块区分');
assert.match(source, /function loveCount\(key\)[\s\S]{0,1600}for \(let m = 1; m <= 12/, '年假期数/年爱心数应统计当年全部12个月');
assert.match(source, /function loveCount\(key\)[\s\S]{0,2000}yearTotal/, '年统计应累计到 yearTotal');
assert.match(source, /'休假': 'leave'/, '休假序列应默认绑定 leave 身份');
assert.match(source, /categoryNames\.indexOf\('休假'\) === -1\) categoryNames\.push\('休假'\)/, '好习惯追踪应自动追加休假序列');
assert.match(source, /push\('休假'\);\s*\n\s*if \(isActionGoodHabitPage && !goodHabitRoles\['休假'\]/, '追加休假序列后应立即补写 leave 身份');
assert.match(source, /push\('休假'\);\s*\n\s*if \(isActionGoodHabitPage && !goodHabitRoles\['休假'\]/, '追加休假序列后应立即补写 leave 身份');
assert.match(source, /id="leaveTablePanel"/, '应包含休假记录表容器');
assert.match(source, /leaveTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'leave'/, '休假表应按序列身份显示');
assert.match(source, /function isLeaveStatSequence\(\) \{ return isActionGoodHabitPage && habitRole\(currentCategory\) === 'leave'; \}/, '休假序列判定应按序列身份');
assert.match(source, /function leaveCheckKey\(day, field\)/, '应有休假日期键函数');
assert.match(source, /function toggleLeaveCheck[\s\S]{0,300}saveState\(\)/, '休假日圆点点击后应保存');
assert.match(source, /function toggleLeaveCheck[\s\S]{0,400}renderLeaveTable\(\)/, '点击休假日后应刷新休假表');
assert.match(source, /function setLeaveReason[\s\S]{0,400}saveState\(\)/, '休假原因输入后应保存');
assert.match(source, /function setLeaveReason[\s\S]{0,500}updateSleepStatCards\(\)/, '休假原因输入后应刷新统计方块');
assert.match(source, /function renderLeaveTable\(\)/, '应有休假表渲染函数');
assert.match(source, /function renderLeaveTable[\s\S]{0,800}休假记录表/, '休假表标题应为休假记录表');
assert.match(source, /table\.className = 'sleep-table leave-table'/, '休假表应附加 leave-table 类');
assert.match(source, /<th>日期<\/th><th>休假日<\/th><th>休假原因<\/th>/, '休假表应包含日期/休假日/休假原因表头');
assert.match(source, /leaveChecks\[leaveCheckKey\(day, '日'\)\]/, '休假日圆点应读取已保存状态');
assert.match(source, /state\.leaveChecks = leaveChecks/, '休假日勾选应持久化到存储');
assert.match(source, /state\.leaveReasons = leaveReasons/, '休假原因应持久化到存储');
assert.match(source, /saved\.leaveChecks/, '加载时应恢复休假日勾选');
assert.match(source, /saved\.leaveReasons/, '加载时应恢复休假原因');
assert.match(source, /addEventListener\('input'[\s\S]{0,300}setLeaveReason/, '休假原因应为格内直接输入框');
assert.match(source, /function renderLeaveTable[\s\S]{0,1600}Math\.min\(15, days\)/, '休假表左栏应截到15号');
assert.match(source, /function renderLeaveTable[\s\S]{0,1600}\[\s*16,\s*days\s*\]/, '休假表右栏应从16号起');
assert.match(source, /function renderLeaveTable[\s\S]{0,2000}leave-table-split/, '休假表应拆为并排容器');
assert.match(source, /\.good-habit-page \.leave-table-split \{[^}]*margin-left: -13px/, '休假表应整体向右移动3px');
assert.match(source, /\.good-habit-page \.leave-table-split \.leave-table \+ \.leave-table \{ margin-left: -10px; \}/, '休假第二列表格应再向左移动5px');
assert.match(source, /\.good-habit-page \.sleep-table\.leave-table th:last-child[^}]*width: 50px/, '休假原因列应收窄到50px');
assert.match(source, /\.good-habit-page \.leave-cell-input \{[^}]*border: 0/, '休假原因输入格应无边框嵌入单元格');
assert.match(source, /if \(isLeaveStatSequence\(\)\) \{[\s\S]{0,240}'月休假数'[\s\S]{0,120}'年休假数'[\s\S]{0,80}''/, '休假序列前两方块为月/年休假数且后两块空白');
assert.match(source, /function countFor\(key\)[\s\S]{0,900}isLeaveStatSequence\(\)[\s\S]{0,60}leaveCount\(key\)/, '休假序列方块计数应来自月/年统计');
assert.match(source, /function leaveCount\(key\)/, '应有休假月年统计函数');
assert.match(source, /function leaveCount\(key\)[\s\S]{0,900}key === 'total'[\s\S]{0,400}leaveCheckKey\(day/, '月休假数应统计当月休假日');
assert.match(source, /function leaveCount\(key\)[\s\S]{0,1800}for \(let m = 1; m <= 12/, '年休假数应统计当年全部12个月');
assert.match(source, /function leaveCount\(key\)[\s\S]{0,2200}return ''/, '休假后两方块计数应留白');
assert.match(source, /function shiftSleepMonth[\s\S]{0,900}renderLeaveTable\(\)/, '切换月份应同步刷新休假表');
assert.match(source, /renderLearnTable\(\);\s*\n\s*renderLoveTable\(\);\s*\n\s*renderLeaveTable\(\);\s*\n\s*renderBadHabitTable\(\);\s*\n\s*\}/, 'render 应调用坏习惯表渲染');
assert.match(source, /purchaseButton'\)\.hidden = hideGoodHabitControls/, '好习惯追踪所有序列应隐藏加号左侧按钮');
assert.match(source, /sectionAddButton'\)\.hidden = hideGoodHabitControls/, '好习惯追踪所有序列应隐藏加号按钮');
assert.match(source, /travelOverviewButton'\)\.hidden = pageType !== 'travel' \|\| hideGoodHabitControls/, '好习惯追踪所有序列应隐藏顶部第三个按钮');
assert.match(source, /sectionTitle'\)\.hidden = hideGoodHabitControls/, '好习惯追踪所有序列应隐藏当前序列标题按钮');
assert.match(source, /purchaseButton'\)\.hidden = hideGoodHabitControls/, '好习惯追踪所有序列应隐藏采购按钮');
assert.match(source, /sectionAddButton'\)\.hidden = hideGoodHabitControls/, '好习惯追踪所有序列应隐藏新增按钮');
assert.match(source, /var hideGoodHabitControls = isActionGoodHabitPage \|\| isActionBadHabitPage \|\| isActionIncomePage/, '收入开支应与好习惯一样隐藏顶部三按钮');
assert.match(source, /isGoodHabitPage\) sleepTableVisible = isActionGoodHabitPage && habitRole\(currentCategory\) === 'sleep'/, '睡眠检测表应按序列身份显示，重排后仍跟随');
assert.match(source, /function habitRole\(/, '应有好习惯序列身份查询函数');
assert.match(source, /goodHabitRoles/, '序列身份应映射存储');
assert.match(source, /var state = \{[\s\S]{0,800}goodHabitRoles: goodHabitRoles/, '序列身份应持久化到存储');
assert.match(source, /saved\.goodHabitRoles/, '加载时应恢复序列身份');
assert.match(source, /function renameCategory[\s\S]{0,500}goodHabitRoles\[newName\] = goodHabitRoles\[oldName\]/, '重命名序列时应同步迁移身份映射');
assert.match(source, /function reorderCategory[\s\S]{0,450}render\(\)/, '重排序列后应刷新右侧界面');
assert.match(source, /var isActionBadHabitPage = returnSub === 'sub3a' \|\| storageKey === 'personal-life-hub-custom-sub3a-v1'/, '坏习惯禁止应按入口与存储键识别');
assert.match(source, /savedReturnTitle === '坏习惯禁止' \|\| customTitle === '坏习惯禁止'/, '坏习惯禁止应按子主题名称识别');

assert.match(source, /if \(isActionBadHabitPage && categoryNames\.length > 1\)[\s\S]{0,200}categoryNames = \[keepName\]/, '坏习惯禁止加载后只应保留一个序列');
assert.match(source, /addCategoryButton'\)\.hidden = isActionBadHabitPage \|\| isActionIncomePage/, '坏习惯与收入开支都应隐藏左侧新增序列按钮');
assert.match(source, /if \(isActionBadHabitPage\) document\.body\.classList\.add\('action-bad-habit-page'\)/, '坏习惯禁止应挂专用样式标记');
assert.match(source, /\.action-bad-habit-page #sectionTitle,\s*\.action-bad-habit-page #purchaseButton,\s*\.action-bad-habit-page #sectionAddButton \{ display: none !important; \}/, '坏习惯禁止应强制隐藏中间标题与加号按钮');
assert.match(source, /if \(isActionBadHabitPage\) document\.body\.classList\.add\('good-habit-page'\)/, '坏习惯禁止应复用好习惯表格样式');
assert.match(source, /id="badHabitTablePanel"/, '应包含坏习惯记录表容器');
assert.match(source, /var badHabitFields = \['暴食肥猪', '嗜糖烂脸', '嘴馋口臭', '忧思伤身', '入坑穷X'\]/, '坏习惯表应包含五列字段');
assert.match(source, /var badHabitChecks = \{\}/, '应有坏习惯勾选存储');
assert.match(source, /function badHabitCheckKey\(day, field\)/, '应有坏习惯日期键函数');
assert.match(source, /function toggleBadHabitCheck[\s\S]{0,300}saveState\(\)/, '坏习惯圆点点击后应保存');
assert.match(source, /function toggleBadHabitCheck[\s\S]{0,400}renderBadHabitTable\(\)/, '点击坏习惯格后应刷新坏习惯表');
assert.match(source, /function toggleBadHabitCheck[\s\S]{0,500}updateSleepStatCards\(\)/, '勾选坏习惯后应刷新统计方块');
assert.match(source, /function renderBadHabitTable\(\)/, '应有坏习惯表渲染函数');
assert.match(source, /function renderBadHabitTable[\s\S]{0,800}穷逼懒货十宗罪/, '坏习惯表标题应为穷逼懒货十宗罪');
assert.match(source, /table\.className = 'sleep-table bad-habit-table'/, '坏习惯表应附加 bad-habit-table 类');
assert.match(source, /<th>日期<\/th><th>暴食肥猪<\/th><th>嗜糖烂脸<\/th><th>嘴馋口臭<\/th><th>忧思伤身<\/th><th>入坑穷X<\/th>/, '坏习惯表应包含日期与五列坏习惯表头');
assert.match(source, /panel\.hidden = !isActionBadHabitPage/, '坏习惯表应仅在坏习惯禁止页面显示');
assert.match(source, /state\.badHabitChecks = badHabitChecks/, '坏习惯勾选应持久化到存储');
assert.match(source, /saved\.badHabitChecks/, '加载时应恢复坏习惯勾选');
assert.match(source, /if \(isActionBadHabitPage\) \{\s*if \(stat\.key === 'total'\) return '哭死得快';\s*if \(stat\.key === 'new'\) return '贪吃是祸';\s*if \(stat\.key === 'discarded'\) return '爱当丑X\?';\s*if \(stat\.key === 'need'\) return '钱才通用';\s*\}/, '坏习惯四方块应使用专属标题');
assert.match(source, /if \(isActionBadHabitPage\) return badHabitCount\(key\)/, '坏习惯页面统计应来自年度累计');
assert.match(source, /function badHabitCount\(key\)/, '应有坏习惯年度统计函数');
assert.match(source, /function badHabitCount\(key\)[\s\S]{0,900}'忧思伤身'/, '哭死得快应统计忧思伤身');
assert.match(source, /function badHabitCount\(key\)[\s\S]{0,900}'暴食肥猪', '嘴馋口臭'/, '贪吃是祸应统计暴食肥猪与嘴馋口臭');
assert.match(source, /function badHabitCount\(key\)[\s\S]{0,900}'嗜糖烂脸'/, '爱当丑X?应统计嗜糖烂脸');
assert.match(source, /function badHabitCount\(key\)[\s\S]{0,900}'入坑穷X'/, '钱才通用应统计入坑穷X');
assert.match(source, /function badHabitCount\(key\)[\s\S]{0,1200}for \(let m = 1; m <= 12/, '坏习惯统计应遍历当年12个月');
assert.match(source, /function shiftSleepMonth[\s\S]{0,1000}renderBadHabitTable\(\)/, '切换月份应同步刷新坏习惯表');
assert.match(source, /renderLeaveTable\(\);\s*\n\s*renderBadHabitTable\(\);\s*\n\s*\}/, 'render 应调用坏习惯表渲染');
assert.match(source, /\.good-habit-page \.sleep-table\.bad-habit-table \{ width: auto; min-width: 0; \}/, '坏习惯表宽度应自适应');
assert.match(source, /\.good-habit-page \.sleep-table\.bad-habit-table th,\s*\n\s*\.good-habit-page \.sleep-table\.bad-habit-table td \{ width: 59px; \}/, '坏习惯表列宽应为59px');
assert.match(source, /\.good-habit-page \.sleep-table\.bad-habit-table th:first-child,\s*\n\s*\.good-habit-page \.sleep-table\.bad-habit-table td:first-child \{ width: 49px;/, '坏习惯表日期列宽应为49px');
assert.match(source, /\.action-bad-habit-page \.sidebar \{ display: none; \}/, '坏习惯禁止应隐藏左侧序列栏');
assert.match(source, /\.action-bad-habit-page \.layout \{[^}]*grid-template-columns: 0 minmax\(0, 1fr\)[^}]*column-gap: 0/, '坏习惯禁止布局应收拢为单列全宽');
assert.doesNotMatch(source, /\.action-bad-habit-page #badHabitTablePanel \{ margin-left: -78px/, '隐藏侧栏后坏习惯表不应再左移');
assert.match(source, /\.action-bad-habit-page #badHabitTablePanel \.sleep-table-wrap \{[^}]*justify-content: center/, '坏习惯表应在页面视图中水平居中');
assert.match(source, /\.action-bad-habit-page #badHabitTablePanel \.sleep-table-title \{[^}]*letter-spacing:/, '坏习惯表标题字间应加空隙');
assert.match(source, /var isActionIncomePage = returnSub === 'sub3c' \|\| storageKey === 'personal-life-hub-custom-sub3c-v1'/, '收入开支应按入口与存储键识别');
assert.match(source, /var isActionLearnProgressPage = returnSub === 'sub3d' \|\| storageKey === 'personal-life-hub-custom-sub3d-v1'/, '学习进度应按入口与存储键识别');
assert.match(source, /savedReturnTitle === '收入开支' \|\| customTitle === '收入开支'/, '收入开支应按子主题名称识别');
assert.match(source, /if \(isActionIncomePage\) document\.body\.classList\.add\('action-income-page'\)/, '收入开支应挂专用样式标记');
assert.match(source, /if \(isActionIncomePage\) document\.body\.classList\.add\('good-habit-page'\)/, '收入开支应复用好习惯表格样式');
assert.match(source, /\.action-income-page #sectionTitle,\s*\.action-income-page #purchaseButton,\s*\.action-income-page #sectionAddButton \{ display: none !important; \}/, '收入开支应强制隐藏中间标题与加号按钮');
assert.match(source, /\.action-learn-progress-page #purchaseButton \{ display: none !important; \}/, '学习进度应隐藏采购清单按钮');
assert.match(source, /if \(isActionLearnProgressPage\) document\.body\.classList\.add\('action-learn-progress-page'\)/, '学习进度应挂载专属页面标记');
assert.match(source, /\.action-income-page \.sidebar \{ display: none; \}/, '收入开支应隐藏左侧序列栏');
assert.match(source, /\.action-income-page \.layout \{[^}]*grid-template-columns: 0 minmax\(0, 1fr\)[^}]*column-gap: 0/, '收入开支布局应收拢为单列全宽');
assert.match(source, /id="incomeTablePanel"/, '应包含收入开支表容器');
assert.match(source, /var incomeValues = \{\}/, '应有每日收入存储');
assert.match(source, /var expenseValues = \{\}/, '应有每日消费存储');
assert.match(source, /var expenseNotes = \{\}/, '应有每日消费备注存储');
assert.match(source, /var savingsBalance = 280000/, '存款总额默认应为280000');
assert.match(source, /state\.incomeValues = incomeValues/, '收入数据应持久化到存储');
assert.match(source, /state\.expenseValues = expenseValues/, '消费数据应持久化到存储');
assert.match(source, /state\.expenseNotes = expenseNotes/, '消费备注应持久化到存储');
assert.match(source, /state\.savingsBalance = savingsBalance/, '存款总额应持久化到存储');
assert.match(source, /saved\.incomeValues/, '加载时应恢复收入数据');
assert.match(source, /saved\.savingsBalance/, '加载时应恢复存款总额');
assert.match(source, /if \(isActionIncomePage\) \{\s*if \(stat\.key === 'total'\) return '存款总额';\s*if \(stat\.key === 'new'\) return '可支配金额';\s*if \(stat\.key === 'discarded'\) return new Date\(\)\.getFullYear\(\) \+ '年总收入';\s*if \(stat\.key === 'need'\) return new Date\(\)\.getFullYear\(\) \+ '年总消费';\s*\}/, '收入开支四方块应使用专属标题');
assert.match(source, /if \(isActionLearnProgressPage\) \{\s*if \(stat\.key === 'total'\) return '学习项目';\s*if \(stat\.key === 'need'\) return '已学完';\s*\}/, '学习进度首尾方块应改为学习项目与已学完');
assert.match(source, /if \(isActionIncomePage\) return incomeCount\(key\)/, '收入开支页面统计应来自收支计算');
assert.match(source, /function incomeCount\(key\)/, '应有收入开支统计函数');
assert.match(source, /function incomeCount\(key\)[\s\S]{0,900}\+ '元'/, '可支配金额应带元并保留正负号');
assert.match(source, /function incomeFieldKey\(day, field\)/, '应有每日收支日期键函数');
assert.match(source, /function setIncomeField[\s\S]{0,400}saveState\(\)/, '收支格输入后应保存');
assert.match(source, /function setIncomeField[\s\S]{0,500}updateSleepStatCards\(\)/, '收支格输入后应刷新统计方块');
assert.match(source, /function renderIncomeTable\(\)/, '应有收入开支表渲染函数');
assert.match(source, /panel\.hidden = !isActionIncomePage/, '收入开支表应仅在收入开支页面显示');
assert.match(source, /function renderIncomeTable[\s\S]{0,900}本月收入共计/, '顶部应显示本月收入共计');
assert.match(source, /function renderIncomeTable[\s\S]{0,1400}本月消费共计/, '顶部应显示本月消费共计');
assert.doesNotMatch(source, /function renderIncomeTable[\s\S]{0,2500}Math\.min\(15, days\)/, '收入开支表不应再按15号分段');
assert.doesNotMatch(source, /function renderIncomeTable[\s\S]{0,2500}\[\s*16,\s*days\s*\]/, '收入开支表不应再拆左右栏');
assert.match(source, /function renderIncomeTable[\s\S]{0,2500}for \(let day = 1; day <= days; day\+\+\)/, '收入开支表应合并为单列竖排日期');
assert.match(source, /function renderIncomeTable[\s\S]{0,1500}income-summary[\s\S]{0,300}本月收入共计[\s\S]{0,200}本月消费共计/, '收入与消费合计标题应同排显示');
assert.match(source, /<th>日期<\/th><th>收入<\/th><th>消费<\/th><th>消费备注<\/th>/, '收入开支表应包含日期、收入、消费、消费备注表头');
assert.match(source, /income-summary/, '合计行应有专用样式类');
assert.match(source, /function shiftSleepMonth[\s\S]{0,1000}renderIncomeTable\(\)/, '切换月份应同步刷新收入开支表');
assert.match(source, /renderLeaveTable\(\);\s*\n\s*renderBadHabitTable\(\);\s*\n\s*renderIncomeTable\(\);/, 'render 应调用收入开支表渲染');
assert.match(source, /dblclick[\s\S]{0,500}savingsBalance/, '存款总额应支持双击行内编辑');
assert.match(source, /blur[\s\S]{0,400}savingsBalance/, '存款总额应在失焦时保存');
assert.match(source, /\.action-income-page #incomeTablePanel \.sleep-table-wrap \{[^}]*justify-content: center/, '收入开支表应在页面视图中水平居中');
assert.match(source, /\.action-income-page #incomeTablePanel \.sleep-table-title \{[^}]*letter-spacing:/, '收入开支表标题字间应加空隙');
assert.match(source, /\.action-income-page #incomeTablePanel \.sleep-table-head \{[^}]*translateY\(-8px\)/, '表头与月份选择应上移8px');
assert.match(source, /\.action-income-page #incomeTablePanel \.sleep-table-head \{[^}]*z-index: 4/, '表头不应被置顶标题条遮盖');
assert.match(source, /\.good-habit-page #incomeTablePanel \.income-summary \{[^}]*translateY\(-4px\)/, '合计标题应上移4px');
assert.match(source, /\.good-habit-page \.sleep-table\.income-table th:first-child,\s*\.good-habit-page \.sleep-table\.income-table td:first-child \{ width: 49px/, '日期列应略宽于标题');
assert.match(source, /\.good-habit-page \.sleep-table\.income-table th:nth-child\(2\),\s*\.good-habit-page \.sleep-table\.income-table td:nth-child\(2\) \{ width: 49px/, '收入列应略宽于标题');
assert.match(source, /\.good-habit-page \.sleep-table\.income-table th:nth-child\(3\),\s*\.good-habit-page \.sleep-table\.income-table td:nth-child\(3\) \{ width: 49px/, '消费列应略宽于标题');
assert.match(source, /\.good-habit-page \.sleep-table\.income-table th:last-child,\s*\.good-habit-page \.sleep-table\.income-table td:last-child \{ width: 94px/, '消费备注列应按标题略宽');
assert.match(source, /\.good-habit-page \.sleep-table\.income-table \{ width: 256px; min-width: 0/, '收入表宽度应为列宽和加5px');
assert.match(source, /\.good-habit-page #incomeTablePanel \.income-summary \{[^}]*color: #806b52[^}]*font-size: 10px[^}]*font-weight: 400[^}]*letter-spacing: 0\.06em/, '合计标题应与方块简介标题同样式');
assert.match(source, /\.good-habit-page \.sleep-table\.income-table th \{[^}]*font-size: 12px[^}]*letter-spacing:/, '收入表头应加大字号并留空隙');
assert.match(source, /if \(key === 'total'\) return savingsBalance >= 10000 \? \(savingsBalance \/ 10000\) \+ 'w' : savingsBalance \+ '元'/, '存款总额超万应以w简写显示');
assert.match(source, /sessionStorage\.setItem\(storageKey/, '保存记录时应同步写入会话存储');
assert.match(renameSource, /sessionStorage\.setItem\(storageKey/, '保存序列时应同步写入会话存储');
assert.match(renameSource, /type=custom&return=/, '新增子主题应进入独立自定义界面');
assert.match(source, /pageType === 'custom'[\s\S]{0,500}personal-life-hub-custom-/, '自定义子主题应使用独立存储空间');
assert.match(source, /function getSavedParentTitle[\s\S]{0,420}personal-life-hub-state-v2[\s\S]{0,180}labels/, '项目标题应读取母页面最新名称');
assert.match(source, /var savedReturnTitle = getSavedParentTitle\(returnSub\)[\s\S]{0,1000}var pageTitle = pageConfig\.title/, '固定模板项目标题也应同步子主题名称');
assert.match(source, /function migrateStorage[\s\S]{0,500}setItem\(targetKey/, '存储迁移应复制旧数据到新空间');
assert.match(source, /pageType === 'other' && returnSub === 'sub1e'[\s\S]{0,180}personal-life-hub-sub1e-v1[\s\S]{0,120}migrateStorage\('personal-life-hub-other-template-v1'/, '重命名的其他入口应迁移到独立数据空间');
assert.match(source, /pageType === 'other' && returnSub !== 'sub1e'[\s\S]{0,100}categoryNames = \['其他'\]/, '独立的其他入口刷新后应保留新增序列');
assert.doesNotMatch(renameSource, /if \(!value\) return;/, '新增子主题名称为空时也应允许确认保存');
assert.match(renameSource, /subEditingLabel\.closest\('\.sub-bar'\)\.hidden = false/, '空白子主题保存后应保留项目入口');
assert.match(renameSource, /state\.visible/, '子主题入口可见状态应持久化');
assert.match(renameSource, /state\.visible\[label\.id\]/, '刷新后应恢复已保存的空白入口');
assert.doesNotMatch(renameSource, /subEditorDeleteButton'\)\.hidden = !label \|\| !label\.textContent\.trim\(\)/, '空白子主题也应显示删除按钮');
assert.match(renameSource, /function createSubBar/, '新增子主题没有预留空位时应动态创建入口');
assert.match(renameSource, /else if \(subAddingCell\)[\s\S]{0,180}createSubBar\(subAddingCell\)/, '新增主题应支持连续创建多个入口');
assert.match(renameSource, /bar = createSubBar\(cell, labelId\);[\s\S]{0,120}var label = document\.getElementById\(labelId\)/, '刷新恢复新增主题时应保留新方块本身');
assert.doesNotMatch(renameSource, /bar = createSubBar\(cell, labelId\)\.parentElement/, '刷新恢复新增主题不能把父节点当作子主题方块');
assert.match(source, /categoryTouchDragging = true/, '序列长按应进入排序状态');
assert.match(source, /function reorderCategory/, '序列应提供排序函数');
assert.match(source, /\.stat-head[\s\S]{0,180}gap: 6px/, '统计数字和简介之间应保留间距');
assert.match(source, /\.stat-name[\s\S]{0,220}letter-spacing:[\s\S]{0,180}transform: translateY\(3px\)/, '统计简介应下移并增加字间距');
assert.match(source, /function countRecordsByMonth/, '应提供按年月统计记录的函数');
assert.match(source, /monthNames = \['Jan', 'Feb'/, '月份明细应使用英文缩写');
assert.match(source, /monthChineseNames = \['一月', '二月', '三月'/, '本月新增标题应使用中文月份');
assert.match(source, /if \(stat\.key === 'new'\) return currentMonthChineseName\(\) \+ '新增'/, '本月新增标题应显示中文月份');
assert.match(source, /function countRecordsByMonth[\s\S]{0,450}newAssignmentsByMonth/, '本月新增应按月份统计');
assert.match(source, /newAssignmentsByMonth/, '新增统计应按年月保存');
assert.match(source, /id="annualYearLabel"/, '年度明细应包含年份选择器');
assert.match(source, /id="annualYearButton"/, '年度明细应通过年份按钮选择年份');
assert.match(source, /id="annualYearPicker"/, '年度明细应提供可滚动年份列表');
assert.match(source, /var firstYear = 2025/, '年份选择应从2025年开始');
assert.match(source, /other:\s*\{[\s\S]{0,220}title: '其他物品', categories: \['其他'\]/, 'Things其他子主题应复刻单序列界面');
assert.match(source, /if \(pageType === 'other' && returnSub !== 'sub1e'\)[\s\S]{0,120}categoryNames = \['其他'\]/, '其他子主题应兼容旧分类数据');
assert.match(source, /\.item \{[^}]*letter-spacing: 0\.06em/, '项目卡片文字应保持统一字间距');
assert.doesNotMatch(source, /id="annualYearUp"|id="annualYearDown"/, '年份按钮两侧不应再有上下调整按钮');
assert.match(source, /\.annual-table[\s\S]{0,180}repeat\(4, minmax/, '年度明细应包含四项统计列');
assert.match(source, /class="control-panel"[\s\S]{0,1200}class="content"/, '页面应分为固定控制区和独立内容区');
assert.match(source, /\.layout[\s\S]{0,180}display: grid[\s\S]{0,180}grid-template-columns: 70px minmax\(0, 1fr\)/, '页面应使用左侧序列和右侧内容的两列布局');
assert.match(source, /\.control-panel \{[^}]*display: contents/, '统计控制区应参与两列网格布局');
assert.match(source, /\.sidebar \{[^}]*grid-column: 1[\s\S]{0,120}grid-row: 1 \/ span 2/, '左侧序列栏应跨越统计和项目两行');
assert.match(source, /\.control-main \{[^}]*grid-column: 2[\s\S]{0,120}grid-row: 1/, '四个统计方块应位于右侧第一行');
assert.match(source, /\.content[\s\S]{0,120}overflow-y: auto/, '下方方块区域应独立滚动');
assert.match(source, /\.section-head[\s\S]{0,180}position: sticky/, '厨具标题应固定在下方区域顶部');
assert.match(source, /\.lower-panel \{[^}]*grid-column: 2[\s\S]{0,120}grid-row: 2/, '项目区域应位于四个统计方块下方');
assert.match(source, /\.lower-sidebar-spacer \{[^}]*display: none/, '项目区域不应再额外保留左侧占位');
assert.match(source, /\.lower-panel[\s\S]{0,180}margin-top: 10px/, '四个统计方块与下方项目区域之间应保留空白');
assert.doesNotMatch(source, /\.lower-panel[^}]*transform:/, '项目区域不应再通过位移固定在屏幕中间');
assert.match(source, /\.content[\s\S]{0,180}overflow-y: auto[\s\S]{0,180}scrollbar-width: none[\s\S]{0,180}-ms-overflow-style: none/, '项目区域应保留滚动并隐藏 Firefox 和旧版滚动条');
assert.match(source, /\.content::-webkit-scrollbar\s*\{\s*display: none;\s*\}/, '项目区域应隐藏 WebKit 滚动条');
assert.match(source, /function setStatAssignment/, '手动统计应提供独立勾选状态处理');
assert.match(source, /type="checkbox"/, '编辑框应使用复选框');
assert.match(source, /stat\.key === 'total'/, '总数应保持自动统计');
assert.doesNotMatch(source, /if \(dragMode === 'item'\) assignToStat\(/, '统计归类不应再依赖拖动');
assert.match(source, /statTypes = \[[\s\S]{0,180}key: 'total'[\s\S]{0,180}key: 'new'[\s\S]{0,180}key: 'discarded'[\s\S]{0,180}key: 'need'/, '统计方块应固定为总数、新增、废弃、添置顺序');
assert.doesNotMatch(source, /card\.draggable = true/, '统计方块不应再支持拖动排序');
assert.doesNotMatch(source, /stat-toggle|statLongPressed|statPressTimer|renderStatDetail/, '统计方块不应再有交互逻辑');
assert.doesNotMatch(source, /className = 'item-option'|options-open/, '项目方块不应再内嵌选项栏');
assert.doesNotMatch(source, /item\.addEventListener\('click'[\s\S]{0,220}openEditor\(record\.id\)/, '单击项目方块不应打开编辑框');
assert.match(source, /item\.addEventListener\('dblclick'[\s\S]{0,180}openItemActionEditor\(record\.id\)/, '项目方块双击应打开紧凑操作框');
assert.match(source, /id="timeInput" type="date"/, '编辑框应直接显示日期字段');
assert.match(source, /timeInput'\)\.value = record && record\.time \? record\.time : ''/, '项目日期默认应为空');
assert.match(source, /created: time \|\| ''/, '未选择日期时不应自动添加日期');
assert.match(source, /使用记录[\s\S]{0,100}id="noteInput"/, '编辑框应包含使用记录字段');
assert.match(source, /id="editNewInput"|编辑新增状态/, '编辑框应包含新增勾选项');
assert.match(source, /id="editDiscardedInput"|编辑废弃状态/, '编辑框应包含废弃勾选项');
assert.match(source, /id="editNeedInput"|编辑添置状态/, '编辑框应包含添置勾选项');
assert.match(source, /\.editor-stat-option[^\{]*\{[\s\S]{0,180}font-size: 12px[\s\S]{0,120}letter-spacing:/, '三个状态按钮文字应略微放大并增加字间距');
assert.match(source, /function countFor[\s\S]{0,800}statIds\(key\)/, '顶部统计应根据项目勾选状态计数');
assert.match(source, /function activeRecords[\s\S]{0,300}discardedIds[\s\S]{0,220}needIds/, '厨具总数应排除已废弃和需添置项目');
assert.match(source, /if \(key === 'total'\) return isActionLearnProgressPage \? categoryNames\.length : activeRecords\(\)\.length/, '学习项目方块应统计序列数量');
assert.match(source, /\.item\.need-item[\s\S]{0,220}background-color: #ead8bc[\s\S]{0,100}background-blend-mode: multiply[\s\S]{0,100}color: #f3e4ca/, '需添置项目应复用第10年方块的底色混合效果和奶白色文字');
assert.match(source, /statIds\('need'\)[\s\S]{0,120}classList\.add\('need-item'\)/, '项目应根据需添置状态使用深色样式');
assert.match(source, /\.item\.discarded-item[\s\S]{0,180}outline: 1px dashed #b85149/, '已废弃项目应显示红色虚线外框');
assert.doesNotMatch(source, /\.item\.discarded-item \.item-time/, '已废弃项目日期不应沿用深色项目的浅色日期');
assert.match(source, /statIds\('discarded'\)[\s\S]{0,140}classList\.add\('discarded-item'\)/, '项目应根据已废弃状态增加红色虚线框');
assert.match(source, /function categoryHasNeed[\s\S]{0,300}statIds\('need'\)/, '应能检测序列内是否存在需添置项目');
assert.match(source, /categoryHasNeed\(name\)[\s\S]{0,100}need-category/, '左侧序列应根据需添置项目增加样式');
assert.match(source, /\.category\.need-category[\s\S]{0,220}background-color: #ead8bc[\s\S]{0,100}background-blend-mode: multiply[\s\S]{0,100}color: #f3e4ca/, '有需添置项目的序列应同步使用第10年方块的底色混合效果和奶白色文字');
assert.doesNotMatch(source, /\.category\.need-category[^}]*outline:/, '左侧序列不应显示红色虚线外框');
assert.match(source, /\.item-name[\s\S]{0,180}letter-spacing: 0\.12em/, '项目名称文字应使用明显字间距');
assert.match(source, /\.item-time[\s\S]{0,220}letter-spacing: 0\.04em/, '项目日期文字应增加字间距');
assert.match(source, /querySelector\('\.stat-count'\)[\s\S]{0,80}countFor\(key\)/, '勾选状态变化后应立即更新顶部统计');
assert.match(source, /class="section-title wood-surface wood-3d"/, '厨具名称应使用木制按钮视觉');
assert.match(source, /id="sectionAddButton"/, '厨具标题右侧应有木制加号按钮');
assert.match(source, /id="purchaseButton"/, '食材厨具应提供采购清单按钮');
assert.match(source, /getElementById\('purchaseButton'\)\.textContent\s*=\s*pageType === 'travel' \? '计划出行' : \(/, '旅行标记应显示计划出行按钮');
assert.match(source, /\['sub2d', 'sub2f'\]\.indexOf\(returnSub\) !== -1 \|\| \/\^\(sub3\|sub4\|cell3-\|cell4-\)\/\.test\(returnSub\) \? '清单' : '采购清单'/, 'Action与Mind母主题应显示清单按钮，其他非旅行主题仍显示采购清单');
assert.match(source, /\['sub2d', 'sub2f'\]\.indexOf\(returnSub\) !== -1/, '未来规划、备忘录与Action、Mind母主题应使用清单按钮名称');
assert.match(source, /document\.querySelector\('#purchaseModal h3'\)\.textContent\s*=\s*isTravel \? '计划出行' : \(\['sub2d', 'sub2f'\]\.indexOf\(returnSub\) !== -1 \|\| \/\^\(sub3\|sub4\|cell3-\|cell4-\)\/\.test\(returnSub\) \? '清单' : '采购清单'\)/, 'Action与Mind母主题的采购弹窗标题应改为清单');
assert.doesNotMatch(source, /getElementById\('purchaseButton'\)\.hidden = pageType !== 'kitchen'/, '所有Things子主题都应显示采购清单按钮');
assert.match(source, /id="purchaseModal"/, '采购清单应使用独立弹窗');
assert.match(source, /function renderPurchaseList/, '采购清单应汇总所有序列的需添置项目');
assert.match(source, /purchaseButton[\s\S]{0,180}openPurchaseList/, '采购清单按钮应打开清单');
assert.match(source, /\.purchase-modal \.editor \{[^}]*width: 360px[^}]*max-height: 88vh/, '采购清单弹窗应放大并限制高度');
assert.match(source, /\.purchase-table-wrap \{[^}]*overflow-y: auto[^}]*scrollbar-width: none/, '采购清单内容应支持纵向滚动');
assert.match(source, /\.purchase-table input \{[^}]*vertical-align: middle/, '采购清单勾选框应在表格中对齐');
assert.match(source, /\.purchase-table input \{[^}]*transform: translateY\(6px\)/, '采购清单勾选框应上移2像素');
assert.match(source, /\.purchase-table button \{[^}]*background: transparent/, '备注铅笔应直接显示在表格底色上');
assert.match(source, /\.purchase-table td:nth-child\(2\) \{[^}]*text-align: center/, '采购清单名称应居中显示');
assert.match(source, /\.purchase-table th:nth-child\(2\) \{[^}]*text-align: center/, '名称菜单标题应居中显示');
assert.match(source, /\.purchase-table th:nth-child\(2\), \.purchase-table td:nth-child\(2\) \{[^}]*transform: translateX\(-5px\)/, '名称标题和内容应向左移动5像素');
assert.match(source, /\.purchase-table th:last-child, \.purchase-table td:last-child \{[^}]*transform: translateX\(12px\)/, '类别标题和内容应向左移动8像素');
assert.match(source, /\.purchase-table \{[^}]*width: calc\(100% \+ 8px\)/, '勾选框名称备注区域右侧应增加8像素');
assert.match(source, /\.purchase-table th:first-child[^}]*white-space: nowrap/, '勾选框标题应保持单行显示');
assert.match(source, /\.purchase-table tr \{[^}]*background:/, '采购清单每行应使用连续底色');
assert.match(source, /\.purchase-table td \{[^}]*background: transparent/, '采购清单单元格不应切断行底色');
assert.match(source, /\.purchase-table button \{[^}]*font-size: 13px/, '备注文字应与名称文字同样大小');
assert.match(source, /\.purchase-table th:nth-child\(3\), \.purchase-table td:nth-child\(3\) \{[^}]*width: 110px/, '备注列和输入框应加宽');
assert.match(source, /\.purchase-table th:nth-child\(3\), \.purchase-table td:nth-child\(3\) \{[^}]*transform: translateX\(10px\)/, '备注列应再向右移动5像素');
assert.match(source, /\.purchase-table th:nth-child\(2\), \.purchase-table td:nth-child\(2\) \{[^}]*min-width: 125px[^}]*overflow: visible/, '名称列应完整显示长名称');
assert.match(source, /\.category \{[\s\S]{0,180}letter-spacing:/, '类别名称应增加字间距');
assert.match(source, /\.purchase-modal \.editor h3 \{[^}]*letter-spacing:/, '采购清单标题应增加字间距');
assert.match(source, /\.purchase-table th \{[^}]*letter-spacing:/, '采购清单表头应增加字间距');
assert.match(source, /名称[\s\S]{0,100}备注[\s\S]{0,100}类别/, '采购清单表头应增加备注列');
assert.doesNotMatch(source, /window\.prompt\(/, '备注编辑不应调用浏览器输入框');
assert.match(source, /startNoteEdit\(record, noteCell\)/, '采购项目应支持在备注单元格内编辑备注');
assert.match(source, /noteCell\.appendChild\(input\)/, '备注输入框应显示在当前行备注位置');
assert.doesNotMatch(source, /function startNoteEdit\(record\)[\s\S]{0,100}closePurchaseList\(\)/, '备注编辑不应关闭采购清单');
assert.match(source, /noteButton\.textContent = record\.note \|\| '✎'/, '有备注时应替代铅笔显示文字');
assert.doesNotMatch(source, /itemNote\.className = 'item-note'/, '备注不应同步显示在项目方块');
assert.match(source, /id="purchaseTable"/, '采购清单应使用表格容器');
assert.match(source, /勾选框[\s\S]{0,80}名称[\s\S]{0,80}类别/, '采购清单表头应包含勾选框、名称、类别');
assert.match(source, /id="purchaseClearButton"[\s\S]{0,100}id="purchaseSelectAllButton"[\s\S]{0,100}id="purchaseConfirmButton"/, '采购清单底部应提供清空、全选、确定按钮');
assert.match(source, /purchaseChecked/, '采购清单应保存已勾选状态');
assert.match(source, /purchaseCleared/, '采购清单应单独保存表格清空状态');
assert.match(source, /function clearPurchaseList\(\)[\s\S]{0,260}purchaseCleared/, '一键清空应只清除采购表格内部数据');
assert.match(source, /key === 'need'[\s\S]{0,180}delete purchaseCleared\[id\]/, '重新标记需添置时应重新加入采购清单');
assert.match(source, /purchaseCleared\[record\.id\]/, '采购清单应过滤已清空的表格数据');
assert.match(source, /\.purchase-table th \{[^}]*font-size: 13px/, '采购清单表头字体应放大');
assert.match(source, /\.purchase-actions button \{[^}]*font-size: 14px/, '采购清单底部按钮字体应放大');
assert.match(source, /function selectAllPurchaseList\(\) \{[\s\S]{0,500}allChecked[\s\S]{0,120}setPurchaseChecked\(!allChecked\)/, '全选按钮应支持再次点击取消全选');
assert.match(source, /id="purchaseButton"/, '食材厨具应提供采购清单按钮');
assert.match(source, /id="purchaseModal"/, '采购清单应使用独立弹窗');
assert.match(source, /function renderPurchaseList[\s\S]{0,500}statIds\('need'\)/, '采购清单应汇总所有分类的需添置项目');
assert.match(source, /checkbox\.addEventListener\('change'[\s\S]{0,220}purchaseChecked/, '采购清单勾选应只保存清单选择状态');
assert.doesNotMatch(source, /checkbox\.addEventListener\('change'[\s\S]{0,260}setStatAssignment\('need'/, '采购清单勾选不应改变项目需添置状态');
assert.doesNotMatch(source, /function setPurchaseChecked\(checked\)[\s\S]{0,300}setStatAssignment\('need'/, '采购清单全选不应改变项目需添置状态');
assert.doesNotMatch(source, /function setPurchaseChecked\(checked\)[\s\S]{0,420}saveState\(\)/, '全选不应在点击确定前保存');
assert.match(source, /function openPurchaseList\(\)[\s\S]{0,260}openPurchaseDraft/, '打开采购清单应建立临时编辑状态');
assert.match(source, /function closePurchaseList\(\)[\s\S]{0,260}restorePurchaseDraft/, '未点击确定关闭时应撤销采购清单修改');
assert.match(source, /function confirmPurchaseList\(\)[\s\S]{0,180}saveState\(\)[\s\S]{0,100}closePurchaseList/, '确定按钮应保存采购清单修改后关闭');
assert.match(source, /function clearPurchaseList\(\)[\s\S]{0,320}purchaseChecked\[record\.id\][\s\S]{0,180}setStatAssignment\('need', record\.id, false\)/, '采购清单清空已勾选项目时应移除需添置状态');
assert.match(source, /\.section-title[\s\S]{0,180}min-height: 31px/, '厨具标题按钮应略微增加高度');
assert.match(source, /\.section-add[\s\S]{0,180}width: 28px[\s\S]{0,100}min-height: 28px/, '加号按钮应为等高等宽小方块');
assert.match(source, /\.section-title[\s\S]{0,220}letter-spacing:/, '厨具标题文字应增加字间距');
assert.match(source, /\.section-add[\s\S]{0,260}color: #5a4632[\s\S]{0,100}font-size: 20px[\s\S]{0,100}font-weight: 800/, '加号应使用统计数字的颜色和粗度');
assert.match(source, /\.section-title[\s\S]{0,220}font-size: 13px/, '厨具标题文字应略微放大');
assert.match(source, /\.purchase-button \{[^}]*font-size: 13px[^}]*letter-spacing: 0\.06em/, '采购清单文字应与左侧按钮一致');
assert.match(source, /\.purchase-button \{[^}]*font-family: inherit[^}]*font-weight: 500/, '采购清单文字应比左侧按钮略粗');
assert.match(source, /\.category-add[\s\S]{0,260}width: 100%[\s\S]{0,120}min-height: 28px[\s\S]{0,180}color: #5a4632[\s\S]{0,100}font-size: 20px/, '左侧新增按钮应与序列按钮同宽');
assert.doesNotMatch(source, /\.category-add\s*\{[^}]*background: transparent/, '左侧新增按钮不应使用透明底色');
assert.match(source, /\.section-head[\s\S]{0,180}grid-template-columns: repeat\(3/, '标题区应沿用项目方块网格宽度');
assert.doesNotMatch(source, /id="addButton"/, '上方不应再显示文字新增按钮');
assert.doesNotMatch(source, /id="yearlyButton"|id="yearPicker"/, '顶部不应再显示独立年份按钮');
assert.match(source, /getElementById\('sectionTitle'\)\.addEventListener\('click', openAnnualDetail\)/, '厨具标题应可点击打开年度明细');
assert.doesNotMatch(source, /stat-detail|stat\.open/, '统计方块不应再提供点击展开详情');
assert.doesNotMatch(source, /function removeStatAssignment|confirm\(/, '统计明细只展示，不应提供删除确认逻辑');
assert.match(source, /\.stat[\s\S]{0,180}min-height: 69px/, '统计方块应恢复初始高度');
assert.match(source, /\.section-title[\s\S]{0,180}min-height: 31px/, '厨具标题高度应略微增加');
assert.match(source, /\.lower-panel[\s\S]{0,180}margin-top: 10px/, '四个统计方块与下方项目区域之间应保留空白');
assert.match(source, /\.annual-head h3[\s\S]{0,120}margin: 12px 0 0[\s\S]{0,120}letter-spacing:/, '年度明细标题应下移并增加字间距');
assert.match(source, /<button class="annual-year-button" id="annualYearButton"/, '年份应以标题右侧纯数字形式展示');
assert.doesNotMatch(source, /class="annual-year-button wood-surface wood-3d"/, '年份数字不应带木制按钮效果');
assert.match(source, /\.annual-year-button[\s\S]{0,240}font-size: 14px[\s\S]{0,120}transform: translateX\(-2px\)/, '年份数字应保持14px并向左移动2px');
assert.match(source, /\.annual-year-picker[\s\S]{0,180}left: 50%[\s\S]{0,120}transform: translateX\(-50%\)/, '年份选择面板应以年份数字为中心向下展开');
assert.match(source, /\.annual-head[\s\S]{0,180}justify-content: flex-start/, '年份按钮应放置在年度明细标题右侧');
assert.match(source, /\.annual-modal \.editor-actions \{[^}]*transform: translateY\(5px\)/, '年度明细关闭按钮框应下移5px');
assert.match(source, /\.annual-year-list[\s\S]{0,160}scrollbar-width: none/, '年份列表应隐藏滚动条');
assert.match(source, /monthlyStats\s*=\s*\{/, '应保存按年月划分的统计快照');
assert.match(source, /function refreshCurrentMonthSnapshot/, '应提供当前月份快照更新函数');
assert.match(source, /function renderAnnualDetail/, '应提供年度明细渲染函数');
assert.match(source, /monthNames\.forEach[\s\S]{0,500}total[\s\S]{0,500}new[\s\S]{0,500}discarded[\s\S]{0,500}need/, '年度明细应按月份展示四项统计');
assert.match(source, /\.annual-cell\.head[\s\S]{0,220}font-size: 12px[\s\S]{0,120}letter-spacing:/, '年度统计表头应放大并增加字间距');
assert.match(source, /\.annual-cell\.head[\s\S]{0,300}wood-surface|className = 'annual-cell head wood-surface wood-3d'/, '年度统计表头应使用木制按钮视觉');
assert.match(source, /editNeedLabel'\)\.textContent = isTravel \? '多次踏足' : isActionLearnProgressPage \? '已学完' : '添置'/, '学习进度编辑框勾选应显示已学完');
assert.match(source, /\['月份', '总数', '本月新增', '已废弃', isActionLearnProgressPage \? '已学完' : '需添置'\]/, '学习进度年度明细末列应显示已学完');

console.log('厨房模板功能约束通过');
