const fs = require('fs');
const assert = require('assert');

const source = fs.readFileSync(__dirname + '/wood-kitchen-template.html', 'utf8');

assert.match(source, /statAssignments\s*=\s*\{\s*new:\s*\[\]/, '统计状态应包含本月新增集合');
assert.doesNotMatch(source, /if \(\['new', 'discarded', 'need'\][\s\S]{0,120}push\(dragId\)/, '本月新增不能通过拖动计数');
assert.doesNotMatch(source, /key === 'new'[\s\S]{0,220}statAssignments\.new\.indexOf/, '本月新增不能依赖拖动集合');
assert.match(source, /id="addCategoryButton"/, '左侧应有新增分类加号按钮');
assert.match(source, /function renameCategory/, '分类应支持重命名');
assert.match(source, /function deleteCategory/, '分类应支持删除');
assert.match(source, /button\.addEventListener\('dblclick'[\s\S]{0,180}openCategoryEditor\(name\)/, '序列应通过双击打开编辑窗口');
assert.match(source, /id="categoryNameInput"/, '序列编辑窗口应包含重命名输入框');
assert.match(source, /id="categoryDeleteButton"[\s\S]{0,100}id="categoryCancelButton"[\s\S]{0,100}id="categorySaveButton"/, '序列编辑窗口底部应依次提供删除、取消、保存');
assert.match(source, /categoryDeleteButton'\)\.addEventListener\('click'[\s\S]{0,180}deleteCategory\(editingCategory\)/, '删除按钮应删除当前序列');
assert.doesNotMatch(source, /button\.addEventListener\('click'[\s\S]{0,180}renderCategories\(\)[\s\S]{0,80}render\(\)/, '序列单击不应在双击完成前替换按钮节点');
assert.match(source, /function openCategoryEditor[\s\S]{0,700}categoryNameInput/, '序列重命名应在编辑窗口显示输入框');
assert.match(source, /categoryTouchDragging = true/, '序列长按应进入排序状态');
assert.match(source, /function reorderCategory/, '序列应提供排序函数');
assert.match(source, /\.stat-head[\s\S]{0,180}gap: 6px/, '统计数字和简介之间应保留间距');
assert.match(source, /\.stat-name[\s\S]{0,220}letter-spacing:[\s\S]{0,180}transform: translateY\(3px\)/, '统计简介应下移并增加字间距');
assert.match(source, /function countRecordsByMonth/, '应提供按年月统计记录的函数');
assert.match(source, /monthNames = \['Jan', 'Feb'/, '月份明细应使用英文缩写');
assert.match(source, /monthChineseNames = \['一月', '二月', '三月'/, '本月新增标题应使用中文月份');
assert.match(source, /if \(stat\.key === 'new'\) return currentMonthChineseName\(\) \+ '新增'/, '本月新增标题应显示中文月份');
assert.match(source, /function countRecordsByMonth[\s\S]{0,450}newAssignmentsByMonth/, '本月新增应按月份统计');
assert.match(source, /newAssignmentsByMonth/, '新增统计应按年月保存');
assert.match(source, /id="annualYearLabel"/, '年度明细应包含年份选择器');
assert.match(source, /id="annualYearButton"/, '年度明细应通过年份按钮选择年份');
assert.match(source, /id="annualYearPicker"/, '年度明细应提供可滚动年份列表');
assert.match(source, /var firstYear = 2025/, '年份选择应从2025年开始');
assert.match(source, /other:\s*\{[\s\S]{0,220}title: '其他物品', categories: \['其他'\]/, 'Things其他子主题应复刻单序列界面');
assert.match(source, /if \(pageType === 'other'\) \{[\s\S]{0,120}categoryNames = \['其他'\]/, '其他子主题应兼容旧分类数据');
assert.match(source, /\.item \{[^}]*letter-spacing: 0\.06em/, '项目卡片文字应保持统一字间距');
assert.doesNotMatch(source, /id="annualYearUp"|id="annualYearDown"/, '年份按钮两侧不应再有上下调整按钮');
assert.match(source, /\.annual-table[\s\S]{0,180}repeat\(4, minmax/, '年度明细应包含四项统计列');
assert.match(source, /class="control-panel"[\s\S]{0,1200}class="content"/, '页面应分为固定控制区和独立内容区');
assert.match(source, /\.layout[\s\S]{0,180}display: grid[\s\S]{0,180}grid-template-columns: 70px minmax\(0, 1fr\)/, '页面应使用左侧序列和右侧内容的两列布局');
assert.match(source, /\.control-panel \{[^}]*display: contents/, '统计控制区应参与两列网格布局');
assert.match(source, /\.sidebar \{[^}]*grid-column: 1[\s\S]{0,120}grid-row: 1 \/ span 2/, '左侧序列栏应跨越统计和项目两行');
assert.match(source, /\.control-main \{[^}]*grid-column: 2[\s\S]{0,120}grid-row: 1/, '四个统计方块应位于右侧第一行');
assert.match(source, /\.content[\s\S]{0,120}overflow-y: auto/, '下方方块区域应独立滚动');
assert.match(source, /\.section-head[\s\S]{0,180}position: sticky/, '厨具标题应固定在下方区域顶部');
assert.match(source, /\.lower-panel \{[^}]*grid-column: 2[\s\S]{0,120}grid-row: 2/, '项目区域应位于四个统计方块下方');
assert.match(source, /\.lower-sidebar-spacer \{[^}]*display: none/, '项目区域不应再额外保留左侧占位');
assert.match(source, /\.lower-panel[\s\S]{0,180}margin-top: 10px/, '四个统计方块与下方项目区域之间应保留空白');
assert.doesNotMatch(source, /\.lower-panel[^}]*transform:/, '项目区域不应再通过位移固定在屏幕中间');
assert.match(source, /\.content[\s\S]{0,180}overflow-y: auto[\s\S]{0,180}scrollbar-width: none[\s\S]{0,180}-ms-overflow-style: none/, '项目区域应保留滚动并隐藏 Firefox 和旧版滚动条');
assert.match(source, /\.content::-webkit-scrollbar\s*\{\s*display: none;\s*\}/, '项目区域应隐藏 WebKit 滚动条');
assert.match(source, /function setStatAssignment/, '手动统计应提供独立勾选状态处理');
assert.match(source, /type="checkbox"/, '编辑框应使用复选框');
assert.match(source, /stat\.key === 'total'/, '总数应保持自动统计');
assert.doesNotMatch(source, /if \(dragMode === 'item'\) assignToStat\(/, '统计归类不应再依赖拖动');
assert.match(source, /statTypes = \[[\s\S]{0,180}key: 'total'[\s\S]{0,180}key: 'new'[\s\S]{0,180}key: 'discarded'[\s\S]{0,180}key: 'need'/, '统计方块应固定为总数、新增、废弃、添置顺序');
assert.doesNotMatch(source, /card\.draggable = true/, '统计方块不应再支持拖动排序');
assert.doesNotMatch(source, /stat-toggle|statLongPressed|statPressTimer|renderStatDetail/, '统计方块不应再有交互逻辑');
assert.doesNotMatch(source, /className = 'item-option'|options-open/, '项目方块不应再内嵌选项栏');
assert.match(source, /item\.addEventListener\('click'[\s\S]{0,220}openEditor\(record\.id\)/, '单击项目方块应直接打开编辑框');
assert.doesNotMatch(source, /item\.addEventListener\('dblclick'/, '项目方块不应再依赖双击编辑');
assert.match(source, /id="timeInput" type="date"/, '编辑框应直接显示日期字段');
assert.match(source, /timeInput'\)\.value = record && record\.time \? record\.time : ''/, '项目日期默认应为空');
assert.match(source, /created: time \|\| ''/, '未选择日期时不应自动添加日期');
assert.match(source, /使用记录[\s\S]{0,100}id="noteInput"/, '编辑框应包含使用记录字段');
assert.match(source, /id="editNewInput"|编辑新增状态/, '编辑框应包含新增勾选项');
assert.match(source, /id="editDiscardedInput"|编辑废弃状态/, '编辑框应包含废弃勾选项');
assert.match(source, /id="editNeedInput"|编辑添置状态/, '编辑框应包含添置勾选项');
assert.match(source, /\.editor-stat-option[^\{]*\{[\s\S]{0,180}font-size: 12px[\s\S]{0,120}letter-spacing:/, '三个状态按钮文字应略微放大并增加字间距');
assert.match(source, /function countFor[\s\S]{0,420}statIds\(key\)/, '顶部统计应根据项目勾选状态计数');
assert.match(source, /function activeRecords[\s\S]{0,300}discardedIds[\s\S]{0,220}needIds/, '厨具总数应排除已废弃和需添置项目');
assert.match(source, /if \(key === 'total'\) return activeRecords\(\)\.length/, '厨具总数应使用排除后的有效项目计数');
assert.match(source, /\.item\.need-item[\s\S]{0,220}background-color: #ead8bc[\s\S]{0,100}background-blend-mode: multiply[\s\S]{0,100}color: #f3e4ca/, '需添置项目应复用第10年方块的底色混合效果和奶白色文字');
assert.match(source, /statIds\('need'\)[\s\S]{0,120}classList\.add\('need-item'\)/, '项目应根据需添置状态使用深色样式');
assert.match(source, /\.item\.discarded-item[\s\S]{0,180}outline: 1px dashed #b85149/, '已废弃项目应显示红色虚线外框');
assert.doesNotMatch(source, /\.item\.discarded-item \.item-time/, '已废弃项目日期不应沿用深色项目的浅色日期');
assert.match(source, /statIds\('discarded'\)[\s\S]{0,140}classList\.add\('discarded-item'\)/, '项目应根据已废弃状态增加红色虚线框');
assert.match(source, /function categoryHasNeed[\s\S]{0,300}statIds\('need'\)/, '应能检测序列内是否存在需添置项目');
assert.match(source, /categoryHasNeed\(name\)[\s\S]{0,100}need-category/, '左侧序列应根据需添置项目增加样式');
assert.match(source, /\.category\.need-category[\s\S]{0,220}background-color: #ead8bc[\s\S]{0,100}background-blend-mode: multiply[\s\S]{0,100}color: #f3e4ca/, '有需添置项目的序列应同步使用第10年方块的底色混合效果和奶白色文字');
assert.doesNotMatch(source, /\.category\.need-category[^}]*outline:/, '左侧序列不应显示红色虚线外框');
assert.match(source, /\.item-name[\s\S]{0,180}letter-spacing: 0\.12em/, '项目名称文字应使用明显字间距');
assert.match(source, /\.item-time[\s\S]{0,220}letter-spacing: 0\.04em/, '项目日期文字应增加字间距');
assert.match(source, /querySelector\('\.stat-count'\)[\s\S]{0,80}countFor\(key\)/, '勾选状态变化后应立即更新顶部统计');
assert.match(source, /class="section-title wood-surface wood-3d"/, '厨具名称应使用木制按钮视觉');
assert.match(source, /id="sectionAddButton"/, '厨具标题右侧应有木制加号按钮');
assert.match(source, /\.section-title[\s\S]{0,180}min-height: 31px/, '厨具标题按钮应略微增加高度');
assert.match(source, /\.section-add[\s\S]{0,180}width: 28px[\s\S]{0,100}min-height: 28px/, '加号按钮应为等高等宽小方块');
assert.match(source, /\.section-title[\s\S]{0,220}letter-spacing:/, '厨具标题文字应增加字间距');
assert.match(source, /\.section-add[\s\S]{0,260}color: #5a4632[\s\S]{0,100}font-size: 20px[\s\S]{0,100}font-weight: 800/, '加号应使用统计数字的颜色和粗度');
assert.match(source, /\.section-title[\s\S]{0,220}font-size: 13px/, '厨具标题文字应略微放大');
assert.match(source, /\.category-add[\s\S]{0,260}width: 100%[\s\S]{0,120}min-height: 28px[\s\S]{0,180}color: #5a4632[\s\S]{0,100}font-size: 20px/, '左侧新增按钮应与序列按钮同宽');
assert.doesNotMatch(source, /\.category-add\s*\{[^}]*background: transparent/, '左侧新增按钮不应使用透明底色');
assert.match(source, /\.section-head[\s\S]{0,180}grid-template-columns: repeat\(3/, '标题区应沿用项目方块网格宽度');
assert.doesNotMatch(source, /id="addButton"/, '上方不应再显示文字新增按钮');
assert.doesNotMatch(source, /id="yearlyButton"|id="yearPicker"/, '顶部不应再显示独立年份按钮');
assert.match(source, /getElementById\('sectionTitle'\)\.addEventListener\('click', openAnnualDetail\)/, '厨具标题应可点击打开年度明细');
assert.doesNotMatch(source, /stat-detail|stat\.open/, '统计方块不应再提供点击展开详情');
assert.doesNotMatch(source, /function removeStatAssignment|confirm\(/, '统计明细只展示，不应提供删除确认逻辑');
assert.match(source, /\.stat[\s\S]{0,180}min-height: 69px/, '统计方块应恢复初始高度');
assert.match(source, /\.section-title[\s\S]{0,180}min-height: 31px/, '厨具标题高度应略微增加');
assert.match(source, /\.lower-panel[\s\S]{0,180}margin-top: 10px/, '四个统计方块与下方项目区域之间应保留空白');
assert.match(source, /\.annual-head h3[\s\S]{0,120}margin: 12px 0 0[\s\S]{0,120}letter-spacing:/, '年度明细标题应下移并增加字间距');
assert.match(source, /<button class="annual-year-button" id="annualYearButton"/, '年份应以标题右侧纯数字形式展示');
assert.doesNotMatch(source, /class="annual-year-button wood-surface wood-3d"/, '年份数字不应带木制按钮效果');
assert.match(source, /\.annual-year-button[\s\S]{0,240}font-size: 14px[\s\S]{0,120}transform: translateX\(-2px\)/, '年份数字应保持14px并向左移动2px');
assert.match(source, /\.annual-year-picker[\s\S]{0,180}left: 50%[\s\S]{0,120}transform: translateX\(-50%\)/, '年份选择面板应以年份数字为中心向下展开');
assert.match(source, /\.annual-head[\s\S]{0,180}justify-content: flex-start/, '年份按钮应放置在年度明细标题右侧');
assert.match(source, /\.annual-modal \.editor-actions \{[^}]*transform: translateY\(5px\)/, '年度明细关闭按钮框应下移5px');
assert.match(source, /\.annual-year-list[\s\S]{0,160}scrollbar-width: none/, '年份列表应隐藏滚动条');
assert.match(source, /monthlyStats\s*=\s*\{/, '应保存按年月划分的统计快照');
assert.match(source, /function refreshCurrentMonthSnapshot/, '应提供当前月份快照更新函数');
assert.match(source, /function renderAnnualDetail/, '应提供年度明细渲染函数');
assert.match(source, /monthNames\.forEach[\s\S]{0,500}total[\s\S]{0,500}new[\s\S]{0,500}discarded[\s\S]{0,500}need/, '年度明细应按月份展示四项统计');
assert.match(source, /\.annual-cell\.head[\s\S]{0,220}font-size: 12px[\s\S]{0,120}letter-spacing:/, '年度统计表头应放大并增加字间距');
assert.match(source, /\.annual-cell\.head[\s\S]{0,300}wood-surface|className = 'annual-cell head wood-surface wood-3d'/, '年度统计表头应使用木制按钮视觉');

console.log('厨房模板功能约束通过');
